### ISSUE TITLE
remove `react-markdown` from the Tooltip component

### ISSUE THREAD

**Issue by iAdramelk** [iterative/dvc.org#1045]
Right now Tooltip uses `react-markdown` to render descriptions from `content/docs/glossary.js` to HTML. It was ok then we have to use `react-markdown` to render docs pages, but now we should simplify it.

We can either convert md to html on the server side with `gatsby`, or just replace it with plain html, because right now we only have couple of links and code samples there.

- [ ] Address #1137 after this one.

**Comment by shcheklein** [comment]
We should probably do `We can either convert md to html on the server side with gatsby` . But it feels it won't save us much. Would be great first to do a comparison on how much JS and load time we can shave off with this effort.

**Comment by rogermparent** [comment]
I can do this one in a way similar to the way I did Event expiration: loading the data from `glossary.js` into a GraphQL and processing it at build time will allow us to freely parse the MD into HTML during build time with any method- probably Remark, since we use it in other features similar to this like `descriptionLong`.
