### ISSUE TITLE
blog: add syntax and support for sidebar notes

### ISSUE THREAD

**Issue by elleobrien** [iterative/dvc.org#1117]
Would it be difficult to have a sidebar in the blog, like the grey text in this sample:

![Screen Shot 2020-02-11 at 10 31 05 AM](https://user-images.githubusercontent.com/29716724/74266790-bfdfd700-4cb9-11ea-8cc7-ef19b0ab8d9f.png)

**Comment by julieg18** [comment]
Are we still wanting this feature? cc @iterative/websites, @jendefig

**Comment by jendefig** [comment]
@julieg18 Hmmm....  That's super interesting.  At the moment I don't see a need, but could invent ones! 😃 You could label it as nice to have, but not of immediate priority.

**Comment by rogermparent** [comment]
While not exactly a sidebar, we could introduce the `aside` element and style it with floats to get what I imagine is the standard behavior for having a block appear to the side.

floated to the right and given a max width, it'd be able to display content like this to the side.

If we want the sidebar content to be specifically separated into something like a sidebar area, I'd imagine we can adapt float behavior with static widths to effectively make the article adapt to the presence of `aside`s in the article. A lot of it could be done in CSS, but for CSS-only sidebar style I'd imagine we'd have to get a bit creative with some of the weirder selectors like `~` to ensure articles with and without aside content look good.

**Comment by rogermparent** [comment]
![basic aside screenshot](https://user-images.githubusercontent.com/9111807/148598147-37f646cd-7042-4a4a-ac67-1ff0c593fc30.png)
Threw together basic floating `aside` styles, looks a little rough in this example case but maybe we could tune it around a more real-world example.

**Comment by jendefig** [comment]
@rogermparent Right now I can't think of a reason why we would need this for the blog. In Elle's example, it is interesting for giving context or further details around the technical paragraph.  But do prefer on the right hand side. Also the search function for the blog, I think, is considerably more important, and how would this work/interfere with that?

 Inviting @MKhalusova and @flippedcoder for their thoughts.

**Comment by julieg18** [comment]
> Also the search function for the blog, I think, is considerably more important, and how would this work/interfere with that?

@jendefig If we agree to add this feature, we'll definitely be focusing on the search function and would start this one at a later date :)

**Comment by yathomasi** [comment]
@jendefig Actually we have already started working on search functionality #3198. We need some discussion/work on UI/UX part(where to place and how to show the results). Once that Is sorted we can figure out proper placement for this as well.

**Comment by RCdeWit** [comment]
For the blogpost rewrite I'm doing right now asides would be useful. So definitely interested in this!
https://github.com/iterative/dvc.org/pull/3331

Could also be an alternative for this: https://github.com/iterative/dvc.org/issues/3153

**Comment by julieg18** [comment]
Since the search feature is complete, I'll add a `p2` on this for now! 

> What elements do we want to be limited to the left side or be able to span into the sidebar area as section separators? Header, code blocks, and blockquotes are worth giving this consideration.

Maybe items that don't wrap naturally when their width is smaller? Headers and blockquote will wrap their text if they get smaller, but when code blocks width gets smaller, you have to scroll to see the entire text.

> Are we okay with HTML aside syntax? Do / how would we want to handle giving per-aside options like an offset or explicit width?

For a first iteration, maybe we could just have asides all have the same options like offset and width. But once we update our blog engine (#3076), we'd have a long more control over asides and could introduce options 🤔 

@jendefig and @RCdeWit, what do you think? Also Rob, you mentioned asides could be useful for your blog post. Would you be able to use #3153 instead of an `<aside>`? If so, maybe we should consider focusing on #3153 instead?

**Comment by RCdeWit** [comment]
#3153 is more in line with how I formatted it initially in Notion. If both features take the same amount of work and there are no other considerations, I'd prefer that implementation. Mostly because I think it might be a bit more flexible and useful in other scenarios.

I would consider either implementation nice to have, though. One way or the other it provides a way to visually distinguish main content from sidenotes/extras.

**Comment by julieg18** [comment]
Personally, I prefer #3153 as well. While asides can be useful, they'd only be able to be seen on large screens. On tablets or phones, we'd probably have to move asides into the main document or remove them entirely. #3153, on the other hand, have multiple uses and can be seen from all screen sizes. @iterative/websites, what do you think?

**Comment by jendefig** [comment]
I agree with these assessments @RCdeWit and @julieg18  - Let's focus on https://github.com/iterative/dvc.org/issues/3153!

**Comment by rogermparent** [comment]
On board for #3153, we're already a bit strapped for horizontal space with multiple sidebars so having an `aside` to the side will be difficult to pull off on all but the largest of screens.
