### ISSUE TITLE
docs engine: can open an non-existent page

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1197]
https://dvc.org/doc/user-guide/api-reference/open

it should be 404. I don't know where does it come from (Hexometer found some broken links on this page).

**Comment by shcheklein** [comment]
I wonder if can be related to the deployment we have (we don't prune pages, for example)?

**Comment by rogermparent** [comment]
This is happening because we switched from making doc pages based on the sidebar to making doc pages for all MD files in `content/docs`.

You can see the source file still exists [here](https://github.com/iterative/dvc.org/blob/master/content/docs/user-guide/api-reference/open.md), but before models it was just sitting in the repo as a dead file. Removing this source file will get you the behavior you're looking for. I'll make a quick branch for it.

**Comment by shcheklein** [comment]
Closed by https://github.com/iterative/dvc.org/pull/1206
