### ISSUE TITLE
support: email link is broken

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1201]
in https://dvc.org/support

![image](https://user-images.githubusercontent.com/1477535/80766800-ddc81580-8b0b-11ea-8e7f-47676e1b5cbe.png)

It renders as `href="https://dvc.org/mailto:support@dvc.org"` (that's a 404 of course) but the code is correct so this is engine-related.

Let's check any that no other special links have a similar problem too?

**Comment by jorgeorpinel** [comment]
p.s. this isn't caught by the link checker cc @casperdcl since that's a static analyzer. Any ideas on how to check links on rendered pages easily? 🙂

**Comment by casperdcl** [comment]
:D after discussion with @shcheklein we use `find` (instead of `git ls-files`) in the daily cron job specifically to check rendered pages as well, I believe.

Are the rendered pages perhaps in a different folder not covered yet?

https://github.com/iterative/dvc.org/blob/bbf95ef332d8e422e444ce3c611d1ef750ea7b73/scripts/link-check-git-all.sh#L9-L13

**Comment by jorgeorpinel** [comment]
This rendered pages would only exist in the build where deployed so not sure from that code that they can be caught currently. Plus I'm not sure how static they are, maybe there's lots of React magic so you wouldn't find the final href value in the code itself. Not sure, maybe @fabiosantoscode knows 🙂

**Comment by rogermparent** [comment]
Looks like this is part of the Link component not recognizing mailto links and trying to use Gatsby `Link` on them instead of a regular `a`. I can tidy this one up quickly, I think.

**Comment by jorgeorpinel** [comment]
Thanks @rogermparent
