### ISSUE TITLE
links: option to prevent external icon (for images e.g. buttons)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1246]
To prevent this:

![image](https://user-images.githubusercontent.com/1477535/81114482-bc8a6f00-8ee7-11ea-8047-247953ad7fd1.png)
> From https://dvc.org/doc/user-guide/contributing/docs#development-environment

**Comment by rogermparent** [comment]
You can work around this issue by making a link in explicit HTML instead of Markdown. I have a PR showing how it can fix this issue at #1251

**Comment by shcheklein** [comment]
@rogermparent does it makes sense to keep the ticket open even if we apply workaround? Can we detect this type of links automatically?

**Comment by jorgeorpinel** [comment]
If that's not easy, I think we can close this. We're using the workaround for now.

**Comment by rogermparent** [comment]
It shouldn't be too hard to simply give this a real implementation, but the question is how we do so. If we change it such that external links containing only an image are exempt, do we need to implement the behavior to re-enable the link?

I don't think this issue is anything to worry about currently with the workaround, but is worth bringing up as a concern if at any point we overhaul the blog remark pipeline.

I could implement this behavior in a Remark transformer if it's really wanted, but it looks like selective disabling isn't currently a natively configurable option so I don't believe it's as simple as changing an option.

**Comment by jorgeorpinel** [comment]
Thanks for looking into it Roger. Sounds complicated, I think let's close this for now but feel free to reopen if you feel differently, guys.
