### ISSUE TITLE
community page: events expiration date, do not show irrelevant events

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1277]
Introduce expiration date for the main banner and per event for the events section.

If event/banner no relevant anymore - don't show it.

If no events to show - do not show the whole events section, show some (nicely done) stub - "No upcoming events"

If no banner - do not show banner.

**Comment by andronovhopf** [comment]
I've just made a PR to add a new banner about the mailing page. Maybe when an event expires, default to this banner instead of totally removing banner?

**Comment by rogermparent** [comment]
> I've just made a PR to add a new banner about the mailing page ([#1282](https://github.com/iterative/dvc.org/pull/1282)). Maybe when an event expires, default to this banner instead of totally removing banner?

Sure! I was actually thinking about adding the functionality for having multiple Hero definitions queued up in an array and having the application use the first that isn't expired. This way, we can plan ahead and have these kinds of timed changes apply without worrying about a git merge.

We can also log items that are expired so that we're reminded to remove stale ones and old data doesn't build up in the repo.

**Comment by shcheklein** [comment]
@rogermparent @andronovhopf this sounds perfect!
