### ISSUE TITLE
cmd ref: document new subcommand `remote rename`

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc.org#1301]
Related to issue [iterative/dvc#3599](https://github.com/iterative/dvc/issues/3599).

**Comment by PseudoNerd** [comment]
Is this a relatively cleaner implementation of the `dvc remote modify oldRemote name newRemote` with the same command options as the `dvc modify` command?

**Comment by jorgeorpinel** [comment]
Hi @PseudoNerd no. Check out the core repo this matches: iterative/dvc/issues/3599. `dvc remote modify` is a new subcommand currently being worked on (PR iterative/dvc/pull/3794).

This issue will probably be best addressed by @karajan1001 who is implementing this in the core repo and since it's not finished, yet let's keep looking please. Did you explore the `good-first-issue` label? https://github.com/iterative/dvc.org/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22? `help-wanted` is also a good one to check. Thanks

**Comment by jorgeorpinel** [comment]
p.s.

> Is this a relatively cleaner implementation of the dvc remote modify oldRemote name newRemote

Note that we never had that `name` param available for `dvc remote modify`.

**Comment by karajan1001** [comment]
> Is this a relatively cleaner implementation of the `dvc remote modify oldRemote name newRemote` with the same command options as the `dvc modify` command?

@PseudoNerd 
Sorry for the late reply, and thanks to @jorgeorpinel, I'm a little busy last week.
There is no command `dvc remote modify name` before, renaming the old remote repo is a new feature. Here we follow the similar command `git remote rename`.

**Comment by jorgeorpinel** [comment]
@karajan1001 will you be wiling/able to implement this docs update along with your core repo work? Just to know whether to plan to do it ourselves if not. Thanks either way 🙂

**Comment by karajan1001** [comment]
@jorgeorpinel 

Oh, I planned to solve it this week, but I am more pleased to have some other contributor's help.

**Comment by jorgeorpinel** [comment]
If you're able to do it it's probably the most efficient way since you know exactly how it works. We only need a draft PR on this and we'll fix it up in terms or language etc. so don't worry about it being perfect.

**Comment by karajan1001** [comment]
@jorgeorpinel 
I am just considering writing some introduction to my [PR](https://github.com/iterative/dvc/pull/3794).
