### ISSUE TITLE
Running command in Get-started (connect with code) tutorial returns error message

### ISSUE THREAD

**Issue by MayankGoel28** [iterative/dvc.org#1303]
From https://github.com/iterative/dvc.org/blob/master/content/docs/tutorials/get-started/connect-code-and-data.md,
running
```
dvc run -f prepare.dvc -d src/prepare.py -d data/data.xml -o data/prepared python src/prepare.py data/data.xml
```
returns error:
`
ERROR: `-n|--name` is required
`
I was able to fix the error and get the required structure on running tree by running,
```
dvc run -f prepare.dvc           -d src/prepare.py -d data/data.xml     -n prepare      -o data/prepared           python src/prepare.py data/data.xml
```

Should I create a PR for this or is this not really an issue?

**Comment by jorgeorpinel** [comment]
What version of DVC are you using? I think -n is an option of run only in the 1.0 pre-release. Our docs still refer mostly to 0.94

**Comment by MayankGoel28** [comment]
I am using the pre-release. I was directed to do so by someone in the discord.

**Comment by jorgeorpinel** [comment]
Yes that's OK. We will be releasing it soon. It will just make it a little tricky for you to follow the current Get Started, which I'm still working on in order to update it to 1.0. Meanwhile I guess please reach us directly on Discord (#need-help or DM me) if you have problems with 1.0. I'll close this issue but thanks for the report, it will be useful for the updates I'm working on.
