### ISSUE TITLE
user guide: document dvc.lock (DVC 1.0)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1422]
Extracted from https://github.com/iterative/dvc.org/pull/1370#pullrequestreview-427482603

> - [x] ...dvc.yaml cannot contain md5 or etag at all. They are in dvc.lock.

Also from https://github.com/iterative/dvc.org/pull/1370#pullrequestreview-427482065:

> - [x] Strictly speaking, md5 is optional. User could totally remove it and dvc will be fine.
> - [x] dvc.yaml does not have md5, it's in the dvc.lock. For .dvc files, in case of --no-commit for dvc.yaml stages, there should not be a lockfile changes at all.

**Comment by jorgeorpinel** [comment]
@skshetry does dvc.lock support `meta` fields or `# comments`?

**Comment by skshetry** [comment]
No, `dvc.lock` does not support `meta` or comments. They will get overwritten on `sync` later.

**Comment by jorgeorpinel** [comment]
@shcheklein should params.yaml have its own section in the dirs and files guide?

**Comment by shcheklein** [comment]
I think dvc.lock and `params.yaml` are very different to be included into the same ticket even. `params.yaml` is not even so a DVC file "per se", DVC supports parameter dependencies (and by default it reads them from `params.yaml`), it does not dictate, neither provide some specific format for that file.

`dvc.lock` is an similar to package lock in npm, Gemfile.lock in ryby, etc. It locks the deps/outs described in `dvc.yaml`. It's an important part of the pipelines functionality. As a first step can be explained in the same section as `dvc.yaml` - since they are closely related.

**Comment by jorgeorpinel** [comment]
Sounds good. Is this example enough specification of params.yaml or does it need its own subsection in that doc? I can create a separate issue or small PR for that if so.

https://dvc.org/doc/command-reference/params#examples

**Comment by shcheklein** [comment]
@jorgeorpinel I think it's enough for now.
