### ISSUE TITLE
banner breaks positions for other elements

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#1592]
After we introduced the banner we broke a few things: 

<img width="492" alt="Screen Shot 2020-07-18 at 11 30 23 AM" src="https://user-images.githubusercontent.com/3659196/87859486-3a0c2b80-c8ea-11ea-8289-96a942a26dcd.png">

<img width="1438" alt="Screen Shot 2020-07-18 at 11 31 47 AM" src="https://user-images.githubusercontent.com/3659196/87859499-4db79200-c8ea-11ea-84e3-4455bfcd4ec1.png">

**Comment by rogermparent** [comment]
I'm almost done with a fix for this, mostly revolving around making the placeholder grow and shrink while considering the extra height the banner adds.

I originally wanted to move the hamburger icon into the header so it could be vertically centered with `position: absolute`, but then found due to `z-index` issues we would have to sacrifice the "moving button lines" effect that requires one element to be the button in both the header and overlay menu. While it's a trade-off I'd take personally, I decided to opt for keeping all existing functionality by default.
