### ISSUE TITLE
pull: add troubleshooting hints for failed command

### ISSUE THREAD

**Issue by bobertlo** [iterative/dvc.org#1660]
It has been mentioned (https://github.com/iterative/dvc/issues/4316) that the error text when checkout fails after pulling from an out of date remote is not very clear. In attempting to clarify the error (https://github.com/iterative/dvc/pull/4339) it was suggested that a link to a "common issues" page would be helpful.

Looking at the website, I agree that https://dvc.org/doc/user-guide/troubleshooting might be a good place to put this.

**Comment by jorgeorpinel** [comment]
Sure, for now in the core repo please use a link in the form https://error.dvc.org/short-problem-desc. This will redirect to https://dvc.org/doc/user-guide/troubleshooting#short-problem-desc

Then please let us know here what the value of `<short-problem-desc>` ends up being, and a description of the problem/solution (or link to where the solution is described) so this issue is actionable.

> Or, feel free to add the new section in https://github.com/iterative/dvc.org/blob/master/content/docs/user-guide/troubleshooting.md — notice the H2 header in Markdown should be in the form `## Problem title {#short-problem-desc}`

Thanks
