### ISSUE TITLE
warnings and errors in prod deployment

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#1727]
E.g.

```
warning code block language not specified in markdown. applying generic code block

lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory

warning Query takes too long: ...  # Several of these

error Command failed with exit code 1. ...
Error: Command failed: yarn build ...
Retrying with a cleared cache:

error Building static HTML failed for path "/community"

warning Deprecation warning - adding inferred resolver for field CommunityEvent.date. In Gatsby v3, only fields with an explicit directive/extension will get a resolver.

warning There are expired Nodes in community.json!
```

> Taken from the latest deploy log, https://dashboard.heroku.com/apps/dvc-org/activity/builds/598f8b63-09f9-4ce9-aa37-f7545a8d8a45

**Comment by jorgeorpinel** [comment]
Cc @rogermparent 🙂

**Comment by rogermparent** [comment]
I can clear a lot of the easy ones right off, like the inferred resolvers and expired events. I'll have a fix for those up within the hour.

`warning code block language not specified in markdown. applying generic code block` is part of `gatsby-remark-prismjs`, and I was able to squash locally by making a language extension for `text`, which is the keyword for code blocks with no specified language. That'll be in the quick fix.

The one that broke the build here on `/community` is a hard-to-pin-down caching issue that occasionally happens with our custom cache re-use, it's kind of difficult to pin down, but I've been able to re-create a similar issue by stopping a Heroku build and running the cache restore script locally. I think if I focus on it I can find a way to induce the problem in a controlled way on another branch, and then find a way to improve the Community schema so that it stops happening.

The `warning: Query takes too long` ones are primarily related to image generation, particularly on thumbnail pages since they currently generate two slightly differently cropped source sets for each of the eight of so thumbnails on each page. I would think the most obvious fix here would be to use a single image set for everything, doing slight crops via CSS if needed.

I don't know what's up with the lscpu one, other than it seems to only show up in the Heroku environment.

**Comment by jorgeorpinel** [comment]
Hey thanks @rogermparent ! No need to fix everything but it's good to keep an eye on these logs now and then, since like you mention, builds fail occasionally (on PR review apps mostly).

About the image cropping, please open a separate issue if you guys think it's worth it cc @shcheklein
