### ISSUE TITLE
dvc move should work with files in tracked folder

### ISSUE THREAD

**Issue by antonmosin** [iterative/dvc.org#1753]
If I **dvc add** a folder with a file in it and then rename the file,  **dvc move**  throws an error:

`ERROR: failed to move 'old_name.csv'-> 'new_name.csv' - Unable to find DVC-file with output 'old_name.csv`

The only option I see is to rename the file manually and **dvc add** it, which would create another copy in cache. This could be problematic for large files.

Would be nice if **dvc move** could handle this case.

**Comment by jorgeorpinel** [comment]
> If I dvc add a folder with a file in it and then rename the file

DVC is tracking the whole directory in this case. If you make any changes inside, please use `dvc add folder/` again to track the updates 🙂 

See for example https://dvc.org/doc/start/data-versioning#making-changes

> rename the file manually and dvc add it

DVC won't let you do this since it's already tracking the containing directory and outputs (add targets) can't overlap with each other.

Thanks

**Comment by jorgeorpinel** [comment]
Cc @imhardikj please consider this confusion as you review the `move` cmd ref.

**Comment by antonmosin** [comment]
Hi @jorgeorpinel Thank you for the reply.

>> please use dvc add folder/ again to track the updates 🙂

Will DVC create another copy of the file in this case? In this case it's not an issue, but I'm curious in case I had to rename a multi-GB file.

**Comment by jorgeorpinel** [comment]
Good question @antonmosin! No extra copy will be added to cache if the only change is renaming the file, nothing will change in there, basically, as it's addressed by the hash value (MD5) of the file contents. Let me test this workflow to confirm what exactly happens, brb... ⌛

**Comment by antonmosin** [comment]
Thanks! In the meantime, I manually examined folders in .dvc/cache for any new file with recent change, and couldn't find any.

A new .tmp was created in the root of .dvc/cache with some md5 hash value and relative path to the new file name
`[{"md5": "some has", "relpath": "new_filename"}]`

**Comment by jorgeorpinel** [comment]
I'm back. So what happens when you rename a file in a tracked directory is that a new .dir metafile is created in the cache to map this new name with the existing cached contents. No data duplication happens. You can learn more about .dir cache files in https://dvc.org/doc/user-guide/dvc-files-and-directories#structure-of-the-cache-directory.

> A new .tmp was created in the root of .dvc/cache

I don't see this. What version of DVC are you using? Please update to the latest version if possible.

**Comment by antonmosin** [comment]
@jorgeorpinel Thanks a lot! I'm using the 1.6.6. version on Linux. That .tmp file was created (or updated?) in the .dvc/cache. It's hidden, just in case.
