### ISSUE TITLE
How to create "custom Google Cloud project" (something changed?)

### ISSUE THREAD

**Issue by hershkoy** [iterative/dvc.org#1775]
I am trying to follow the instructions to generate a ["custom Google Cloud project"](https://dvc.org/doc/user-guide/setup-google-drive-remote#:~:text=Find%20and%20select%20the%20%22Google,Save%20(scroll%20to%20bottom).) ,  but it seems that something has changed in the google platform.  

The instructions says that  should choose "Other", but this option doesn't exist. See image below.

![image](https://user-images.githubusercontent.com/13259380/92807288-6a8cb500-f3c3-11ea-98fc-8bdfa34115a9.png)

What do I need to choose here?

**Comment by jorgeorpinel** [comment]
Thanks for the report @hershkoy !

@shcheklein should we try to simplify and generalize the guide to avoid mentioning the specific UI options to click on? I'm pretty sure it will continue to change rapidly on Google's side...

**Comment by shcheklein** [comment]
@jorgeorpinel I'm not sure how would that solve the `What do I need to choose here?` problem ...

To give a bit more context on why we decided to do this the way it's done (vs a bit more technical and "dry" docs in other cases) (doesn't mean we can't reconsider this):

- first, we are long due on doing proper instructions for other remotes. GDrive was the first one.
- GDrive is supposed to be the simplest to use and is targeted towards first-time users, the intention was to make as simple as possible to start with it
- setting up a remote is a critical path- it would be among the first things to optimize if we want to make things easier to use

**Comment by sarthakforwet** [comment]
@jorgeorpinel @shcheklein, rather than specifying the specific steps for creating credentials can we provide a link to Google cloud's tutorial of creating credentials for OAuth client ID?

This would be the same as the links provided in steps 2 and 3 of this tutorial.

Google cloud's tutorial can be found [here](https://cloud.google.com/endpoints/docs/frameworks/java/creating-client-ids#web-client).

**Comment by shcheklein** [comment]
@sarthakforwet hey! What steps exactly to do you suggest to change/simplify and how. Sorry, it's not exactly clear. Could you please expand on this a bit?

the link you shared is about Android and Web, though. They are not relevant and misleading in this case.

**Comment by jorgeorpinel** [comment]
I understand the intentions but at the same time I'm not convinced that having how-to docs on what to do on other tools and platforms is sustainable. It's tricky of course because we support all these integrations so we need to explain how to use them.

I wonder if there's a good middle ground where we can avoid all these specific steps and screen shots by using more general concepts from those platforms. If we find good guides published by them on parts of the process like Sarthak suggested, then that would be great too.

We could still publish DVC+{type} guides in external blogs as needed.

---

But anyway, for now we should fix this one guide. Would you like to try updating it @sarthakforwet ?

**Comment by shcheklein** [comment]
>  If we find good guides published by them on parts of the process

Yep, that would be a key here. Until we have a good/simple link(s) we could rely on, I suggest we keep the current guide up to date and consider this ticket as a bug issue.

**Comment by sarthakforwet** [comment]
> the link you shared is about Android and Web, though

Yeah you are right @shcheklein. The tutorial I mentioned is not completely related to the case.

> But anyway, for now we should fix this one guide. Would you like to try updating it @sarthakforwet ?

I'm up for that! Do you have any specifics in mind that should be worked upon?

**Comment by jorgeorpinel** [comment]
The specifics are in the description above and first few comments, thanks.

**Comment by sarthakforwet** [comment]
Step 5 has been changed and it replaced the "Other" with "Desktop app" and that step seemed to be fine for now. 

I think the next change could be to reduce the usage of specifying the direct buttons in the tutorial and make it more generalizable? I think we could also replace the screen shots with GIFs to give more clearer explanation and remove the use of directions like "scroll to bottom", "left sidebar" etc.

**Comment by jorgeorpinel** [comment]
Oh. I guess this was fixed in a PR without linking to the issue.

Should we close this @hershkoy @shcheklein ?

@sahilbhosale63 you're welcome to submit a suggestion PR along the lines you're thinking. Or check out other Hacktoberfest issues if you prefer: https://github.com/iterative/dvc.org/labels/hacktoberfest

**Comment by jorgeorpinel** [comment]
Closing as the original report has been addressed for a while + we haven't gotten complaints since.
