### ISSUE TITLE
logo in a sidebar

### ISSUE THREAD

**Issue by elleobrien** [iterative/dvc.org#2036]
I'm trying to add a new section in the docs sidebar, and with it a new icon. 

The "Home" page has a house icon, which is in `src/components/Documentation/Layout/SidebarMenu`. I've tried adding my own `.svg` to this path so I can give the new CML section of the docs its own distinct icon (the shape of the CML logo). However, my CML icon doesn't render- it shows up as blank space when i try. 

Are there any specifications for the format of sidebar icons? I tried inspecting `house.svg` in Illustrator but this is above my design skills :)

**Comment by shcheklein** [comment]
@rogermparent could you please help us a bit- should not be a big deal, I hope?

**Comment by rogermparent** [comment]
Not a problem! Sidebar icons need to be imported and added to a JS map in the `SidebarMenu` component in `src/components/Documentation/Layout/SidebarMenu/index.tsx` in order to enable their use in the sidebar.

I just added the one we have here and got it working, I'll push it up here once I convert the SVG into the `currentColor`-filled type like the House is.

**Comment by rogermparent** [comment]
Just added it to the linked PR, [here's the deploy preview page](https://dvc-landing-cml-docs-svosyzek8.herokuapp.com/doc/cml)!

**Comment by shcheklein** [comment]
thanks @rogermparent !
