### ISSUE TITLE
Some commands are "unrunnable"

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc.org#204]
For example, the following snippet from: https://dvc.org/doc/commands-reference/metrics

```bash
dvc run -d code/evaluate.py \
        -M data/eval.json \
        -f Dvcfile \
        python code/evaluate.py
```

I can't run the following command because I lack `code/evaluate.py`.

It would be great to have either:
1) The command used above ready to copy paste, for example:
```python
# code/evaluate.py
print("do some evaluation...")
```

2) Use more broad commands that the user can actually copy paste, like `echo` or whatever.

**Comment by shcheklein** [comment]
It's a good question! What are your thoughts, @dmpetrov @robogeek ? 

I personally prefer them to be "executable". Like in `dvc repro` - a simple pipeline out of bash commands. But on the other hand, there is an opinion that we should use some domain that is close to the real-life in all our examples. It's extremely hard to make them executable obviously (that's what get started,  tutorials, full examples are).

We haven't figured out the right balance here still I believe.

**Comment by robogeek** [comment]
Yes I've seen the discussion on the forum asking that the examples be directly executable.

I think the tail end of command documentation is not the place to put an extensive example with all the bells and whistles.  Therefore those examples have to be minimalized using simple tools.  

I also think the example section in command documentation should be seen as a broad example of what might be done, rather than a concrete executable example -- but obviously the voice of the customer as spoken in the forum says differently.

**Comment by robogeek** [comment]
FWIW I've just added a detailed example showing what happens in the cache from a `dvc push` operation.  The example is attached to this pull request:

https://github.com/iterative/dvc.org/pull/203

**Comment by shcheklein** [comment]
@robogeek @mroutis I've updated the `dvc checkout` example here: https://dvc.org/doc/commands-reference/checkout. It should be "runnable". It's a tradeoff in terms of complexity vs keeping it runnable. @mroutis you still need to clone the repo and install requirements to being able to run it. I think we can do `echo`, `wc -l` as well, to show the concept even in a simpler environment.

Let me know what you think guys.

**Comment by shcheklein** [comment]
Duplicate #198
