### ISSUE TITLE
dvc.org seems to contain not-implemented changes

### ISSUE THREAD

**Issue by pared** [iterative/dvc.org#2082]
After talking with @efiop, it seems to me that dvc.org is deploying development version.
Two users have reported not-working functionality which seems to be designated for 2.0:
https://discord.com/channels/485586884165107732/485596304961962003/796664903179698178
https://discord.com/channels/485586884165107732/485596304961962003/796376985362366464

@jorgeorpinel @shcheklein do we have some docs tag that could be deployed until 2.0 is ready?

**Comment by jorgeorpinel** [comment]
Yeah we have merged some 2.0 PRs to master already because it's difficult to manage both without #2006.

There is a `v1` branch I maintain that doesn't have any 2.0 stuff but it's also a bit outdated in other regards. We plan to use that for when we have #2006 but if you guys deem it necessary, we can deploy it to production for now to avoid confusing users.

Another alternative is to add warnings like in https://dvc-landing-2-0-pipelin-enhjqc.herokuapp.com/doc/user-guide/dvc-files/advanced-dvc.yaml but we would need to identify which 2.0 changes have been merged and I don't remember (we could look it up from recent PRs or just based on the used complains above).

I could do any of that. Please lmk @shcheklein

**Comment by jorgeorpinel** [comment]
> https://discord.com/channels/485586884165107732/485596304961962003/796664903179698178
https://discord.com/channels/485586884165107732/485596304961962003/796376985362366464

@pared I checked these 2 (`config --list` and multi-`cmd` dvc.yaml) and trying to insert an alerts seems overkill for those 2 small ones. I think we can probably live with this until the release? 🙂 

The 2.0 dvc.yaml stuff does have the warning for now: https://dvc.org/doc/user-guide/dvc-files/advanced-dvc-yaml

**Comment by pared** [comment]
@jorgeorpinel I guess we can, the main point of this issue was to check whether there was some problem with the deployment of docs. I guess we need to just keep it and ask users to wait a little bit more for those features.

**Comment by jorgeorpinel** [comment]
Agreed, and thanks for the reminder! We haven't forgotten and are tracking 2.0 docs progress in #2026.

Closing this since there's no problem in deployment and to reduce the number of issues outstanding.
