### ISSUE TITLE
exclude $ when copying

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#213]
See https://discordapp.com/channels/485586884165107732/485586884165107734/558281550270038037 .

Is this even possible with our md files?

**Comment by robogeek** [comment]
It looks like the comment is that in the documentation we put

```
$ dvc add foo.txt
```

Meaning, there's a `$` at the front of the line, and the person writing the comment finds that inconvenient.  I can understand the point.

In the `dvc.org` Markdown files it would be trivial to remove those things, just edit the files and remove them.

However ...

This is a longstanding practice by nearly/all authors of documentation for Unix command-line usage.  Use of `$` and `#` at the beginning of command text denotes whether the command is run as a normal user or as `root`.

The person writing the comment seems to believe this is not common practice?  As a user of Unix systems since 1981 (or thereabouts) that my experience is this **IS** common practice.

**Comment by ei-grad** [comment]
> The person writing the comment seems to believe this is not common practice?

No, there is a suggestion to alter the HTML to make it possible to copy the command alone. It looks quite a big effort for a minor issue, as of mine.

**Comment by efiop** [comment]
@robogeek I totally agree with you! I didn't mean to remove $, I meant that it shouldn't be selectable like in https://linuxize.com/post/how-to-set-or-change-timezone-on-debian-9/ .

**Comment by efiop** [comment]
@ei-grad Agreed, I'm wondering if it is a big effort though :)

**Comment by shcheklein** [comment]
there is an ongoing effort to fix this by @ashelkov, hopefully soon.

**Comment by shcheklein** [comment]
it should be possible to do this with JS

**Comment by shcheklein** [comment]
closed by https://github.com/iterative/dvc.org/commit/b50e38c97f8f8433eaeb6df3819aea533c85cbae

**Comment by Suor** [comment]
Sorry for returning to closed issue, but a small imperfection is bothering me:) When we have several `$` command lines the leading space is selected starting from the second one:

![dvc-org-selection](https://user-images.githubusercontent.com/284103/57830017-fd6f0c80-77da-11e9-92db-55c68421162e.png)

**Comment by shcheklein** [comment]
@Suor yep, it's bothering me as well. Let's fix it :)
