### ISSUE TITLE
ref: Update `dvc plots` to include information about offline HTML plots

### ISSUE THREAD

**Issue by pared** [iterative/dvc.org#2402]
After https://github.com/iterative/dvc/pull/5694 we allow users to provide their own HTML templates, for use cases where it does not make sense to use default one (eg isolated environment not having access to internet, and not allowing the download of vega libs).

**Comment by jorgeorpinel** [comment]
Hi

> for use cases where it does not make sense to use default one (eg isolated environment not having access to internet, and not allowing the download of vega libs)

Are there any other use cases? I wonder whether these are kind of edge cases.  Maybe styling the webpage or integrating it to some web app engine?

Cc @iesahin FYI (rel. #2472)

**Comment by jorgeorpinel** [comment]
p.s. or is this specifically for https://github.com/iterative/dvc/issues/5679 ?

**Comment by dberenbaum** [comment]
> p.s. or is this specifically just to address [iterative/dvc#5679](https://github.com/iterative/dvc/issues/5679) ?

This was introduced specifically to address that issue, but I think you are right that we should acknowledge that it can be more generally useful.

**Comment by iesahin** [comment]
I think to refit this issue to update the `dvc plots` ref, and create another issue for a more general guide in UG for plots. The second one will be a general guide for plotting in DVC.

**Comment by iesahin** [comment]
I think not to say _template_ for the HTML file, as there are [too many _template_ references in the document](https://dvc.org/doc/command-reference/plots#plot-templates). Instead I'll add a section for _offline usage_ and tell the new feature there.

**Comment by jorgeorpinel** [comment]
> refit this issue to update the dvc plots ref

I think that's already the case as that is (I think) what #2472 will do, which will close this issue.

> create another issue for a more general guide in UG for plots

Yes 👍 

> not to say template for the HTML file

Interesting idea but... The `config` param is called `plots.html_template` and the CLI option `plots diff --html-template`, so if we don't want to use that term, should we ask @pared whether those names should change in the core repo? I agree it's confusing to call it a template (even when it is) because we already refer to [Vega/JSON templates](https://dvc.org/doc/command-reference/plots#plot-templates) with that word. But what's a better word? "Offline usage" seems like an example about the feature TBH, not it's name.

> add a section for offline usage

I think that could be an Example in the `plots` ref index. The Description could have a short section describing how HTML "templates" (or whatever we call this feature) work e.g. what parameters it accepts (basically `{plot_divs}` I guess). It can be quite short.

**Comment by pared** [comment]
@jorgeorpinel @iesahin I agree that `template` is unfortunate term. Maybe we should just go with `html`?

**Comment by iesahin** [comment]
Although I'm not happy with the naming, we don't have much option here I think. I'll set the section title to "HTML templates" and tell that this is a separate feature.

**Comment by pared** [comment]
@iesahin we could also think about going with pure HTML and chaning the way the "templates" work - my idea would be to remove the requirement for the placeholder and just insert the plots after `<body>` tag. That way we could actually call this option html, because that would be what it accepts.

**Comment by jorgeorpinel** [comment]
> @jorgeorpinel @iesahin I agree that template is unfortunate term. Maybe we should just go with html?

@pared well, it is a template haha. But yes if we can avoid "template" and just use the term "HTML" that should work. So `plots.html` and `plots diff --html`? BTW what about `{plot_divs}`->`{dvc_plots}`?

> remove the requirement for the placeholder and just insert the plots after <body>

👍 but maybe we should move this ideas to https://github.com/iterative/dvc/pull/5694 ? (post-merge review) or a new core issue.

> I'll set the section title to "HTML templates" and tell that this is a separate feature.

That works too @iesahin but maybe it's possible to use `## Custom HTML file` and avoid "template" surrounding this feature. WDYT?
