### ISSUE TITLE
guide: confusion between params (templating) and param dependencies

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#2412]
https://stackoverflow.com/questions/67215839/use-parameters-from-additional-configs-in-dvc-2-0/67221065#comment118833797_67221065

> In [link](https://dvc.org/doc/user-guide/project-structure/pipelines-files#templating) it says "To load additional params files, list them in the top vars, in the desired order, e.g.:". This is where my initial confusion originated from.

We need to be explicit that those could not (?) be used as dependencies. 

(that's comes back to the discussion on parametrization and params - two terms overlap and confuse people)

**Comment by jorgeorpinel** [comment]
Yep, we discussed this. AFAIR we don't want to separate the concepts? Params are params whether you use them as substitutions in a dvc.yaml template or as stage dependencies. But since both go in dvc.yaml in different ways we can def. be more explicit in the UG, would that be enough to solve this issue, or do we want to revisit the terminology itself?
