### ISSUE TITLE
ref: Emphasize multiple `-p` options instead of comma separated parameters in `dvc stage add` (and elsewhere)

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2422]
`dvc stage add` accepts multiple `-p`/`--params` options, so

```
dvc stage add -n prepare \
              -p prepare.seed \
              -p prepare.remix \
              -p prepare.remix_split \
              ...
```

is equivalent to 

```
dvc stage add -n prepare \
                         -p prepare.seed,prepare.remix,prepare.remix_split \
                         ...
```

IMO, the former is more readable (and writable and splittable) than the latter. However, [the docs](https://dvc.org/doc/command-reference/stage/add#options) show comma-separated values as _the_ way to specify multiple parameters. 

```
- `-p [<path>:]<params_list>`, `--params [<path>:]<params_list>` - specify a set
  of [parameter dependencies](/doc/command-reference/params) the stage depends
  on, from a parameters file. This is done by sending a comma separated list as
  argument, e.g. `-p learning_rate,epochs`. The default parameters file name is
  `params.yaml`, but this can be redefined with a prefix in the argument sent to
  this option, e.g. `-p parse_params.yaml:threshold`. See `dvc params` to learn
  more about parameters.
```

I think we should emphasize multiple `-p` options in all examples regarding the parameters.

**Comment by jorgeorpinel** [comment]
Thanks for the idea @iesahin 

This one would probably be easier to address as a PR. Mind sending a draft with your proposed change? At least on one or a few `stage add` examples, and a list of other places you would like to change.

BUT since we have the issue, I should say that IMO multiple `-p`s seems more readable in general. Maybe multiple ones in the `stage add` ref examples, or at least in its first examples (for extra clarity), and condensed ones in later examples or examples in other refs that are not about `stage add`.

**Comment by jorgeorpinel** [comment]
p.s. I see we agree on which one is more readable. So alternatively feel free to make a draft PR changing the description of `stage add -p` (option) so it doesn't seem like multiple ones is the recommended/only way.

**Comment by iesahin** [comment]
I noticed this while writing the new GS pipeline and didn't want to divert my attention. Will return to this certainly. Thanks @jorgeorpinel .
