### ISSUE TITLE
Syntax highlighter for `exp show` tables

### ISSUE THREAD

**Issue by iesahin** [iterative/dvc.org#2516]
`dvc exp show` uses colored/bold titles in its output and probably using colored output will continue in other parts of the software. Currently we use screenshots for these (like in #2497). 

It's better to represent this colored text in `code blocks.` It provides more uniformity.  

The solution should support colored text+background and bold/italic text. 

_Originally posted by @shcheklein in https://github.com/iterative/dvc.org/pull/2497#discussion_r641873974_

**Comment by jorgeorpinel** [comment]
Could be part of the existing `dvc` highlighter.

**Comment by iesahin** [comment]
Is there any chance we can get colorful tables in the code sections? 

@jendefig @rogermparent

**Comment by jendefig** [comment]
I think you meant to tag @julieg18 on this, but I support this effort! 😄

**Comment by iesahin** [comment]
I shouldn't start this before drinking my first coffee ☕  Thank you @jendefig 😄

**Comment by julieg18** [comment]
I think it's possible. We could edit our `prismjs` `dvc` config to check for tables, then add the needed classes to the table headers to change the font/color. 🤔

**Comment by rogermparent** [comment]
I think we can do a lot of this, however some distinctions can't be made from the text output alone, like differing between params and metrics:

![image](https://user-images.githubusercontent.com/9111807/124672756-906cd400-de85-11eb-8b50-82a85f5671f8.png)

You can see here that metrics are yellow and params are blue- we can't really tell which is which from the text alone. If we're okay with having the highlight of the column names all being the same, I'm sure we could figure that out since it just means recognizing the headers surrounded by column borders.

If we want those individual colors, we'll have to toss in some annotation magic where writers specify which columns are params and which are metrics- I have no idea what the most effective way to do that is, but the easiest would be something like prefixing each column header with something like `p:` and `m:` which is removed and replaced with a color BG during processing.

**Comment by iesahin** [comment]
> I have no idea what the most effective way to do that is, but the easiest would be something like prefixing each column header with something like `p:` and `m:` which is removed and replaced with a color BG during processing.

This may be the way to proceed. We can have a `colortable` syntax where `p:` prefix paints a cell blue, and `m:` to yellow, etc. or we can have color prefixes, like `yellow:`, `blue:` and that may be more general. 

It may be possible to copy the terminal control codes for colors from the raw output, but probably it will be error-prone and won't save any work for you.
