### ISSUE TITLE
clarify external data examples

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc.org#2538]
https://dvc.org/doc/user-guide/managing-external-data#examples is a bit confusing to me since the `external-data` in the examples doesn't seem to be used.

Maybe after `dvc add --external` there should be something like `dvc run -d remote://external-data ...`?

Also instead of labelling

1. Config
2. Tracking
3. Create,

it should be more like

1. Config
2. Use cases
  a) Tracking
  b) Create,

unless I've misunderstood something?

**Comment by shcheklein** [comment]
Related #520 

You are not alone :)

Some context:

1. External deps/outs - are advanced features, so we haven't been paying enough attention for now
2. Managing external data was initially named "External outputs" and it was even more confusing - since it was hard to find a basic scenario (I have data on S3 - how do I add it as-is and manage it in place? why is it an output in that case??) So as temp solution we renamed it to be this title and it should be addressed as part of the #520 eventually.
3. This section might include other scenarios eventually - straight to remote, ext outs and ext deps together, external cache probably, etc.

I hope that help a bit :) Let me know if there are more questions now, good to discuss and hear more opinions about this.

I would suggest to continue in #520 though.

**Comment by casperdcl** [comment]
migrated & merged with #2542
