### ISSUE TITLE
Run a CI/CD check that makes sure DVC download links are working on dvc update

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc.org#2579]
* have check make sure links for downloading DVC are working
* we could either run the check after every new dvc release or run it daily

**Comment by jorgeorpinel** [comment]
Can you clarify what "on dvc update" means? And if possible mention what the check would do on the issue title. Thanks

**Comment by julieg18** [comment]
So far I have only possible solution for this ticket:
1. Move download links to an easier to access file.
2. Write a bash script that loops through links checking if links are correct, assigning answer to a variable. I found a way to do that with `curl`:
```
curl -I "https://s3-us-east-2.amazonaws.com/dvc-public/dvc-pkgs/osxpkg/dvc-2.1.0.pkg" 2>&1 | awk '/HTTP\// { print($2 == "200" ? "true" : "false") }'`)
```
3. Run script in Github Actions, and responding according depending on what variable says.

This solution feels kind of overcomplicated to me though. 🤔 Is there a simpler solution to accomplish this task?
cc @rogermparent @shcheklein

**Comment by rogermparent** [comment]
> 1. Move download links to an easier to access file.

Agreed, this will be needed to access them from multiple points. A JSON file with all the different download links should do.

> 2. Write a bash script that loops through links checking if links are correct, assigning answer to a variable. I found a way to do that with `curl`:
> [...]
> This solution feels kind of overcomplicated to me though. thinking Is there a simpler solution to accomplish this task?

Agreed that a bash script isn't the way we want to go, and implementing the actual link checking logic is a nightmare which should be avoided, although a lesser nightmare because all our links are AWS so they should behave consistently.

[Lychee](https://github.com/lycheeverse/lychee) is a relatively popular open-source family of projects built around flexibly checking links, and though it's billed for HTML and MD, it also works in JSON files! I think we can get what we want here by:

1. Making a json file that keeps all our DVC download links, wired into the Gatsby site to feed the current components.

2. Adding a GitHub Workflow that points [the Lychee Action](https://github.com/lycheeverse/lychee-action) to that file, checking all the DVC download links. I think this specific check would be best targeted once per day on master, and on master merges- doing it on every PR seems a bit much, and the diff link checker should handle it, though I suppose in its current state it's unwise to put too much trust it in that project right now.

**Comment by shcheklein** [comment]
Q: we have already our own link checker running every day - does it detect it now?

My2cs - custom Github action with a CLI command to try all specific links in one sounds fine to me also.

**Comment by shcheklein** [comment]
BTW, I think we dynamically generate actual link from the version, or not? @julieg18 could you please share the file where it is handled now?

**Comment by julieg18** [comment]
> [Lychee](https://github.com/lycheeverse/lychee) is a relatively popular open-source family of projects built around flexibly checking links, and though it's billed for HTML and MD, it also works in JSON files! I think we can get what we want here by....

Great idea @rogermparent, I've never seen that package before! 

> BTW, I think we dynamically generate actual link from the version, or not? @julieg18 could you please share the file where it is handled now?

Yes, part of our links are formed in our `[DownloadButton](https://github.com/iterative/dvc.org/blob/master/src/components/DownloadButton/index.tsx#L12)` component, then our `[Link](https://github.com/iterative/dvc.org/blob/3cff2ef91a59884f293f0268b060fe48cb176a2d/src/components/Link/index.tsx#L108)` component uses our `[redirect utils code](https://github.com/iterative/dvc.org/blob/3cff2ef91a59884f293f0268b060fe48cb176a2d/src/utils/shared/redirects.js#L63)` to form the download links that our shown from the page. We'll probably have to end up using some of Lychee's flags and options to be able to scan the urls while keeping our url redirect logic, but I think it's possible!

**Comment by shcheklein** [comment]
Thanks @julieg18 !

Is Lychee similar to the link checker? In a sense that it can only analyze links that are available statically? Or can it actually render the website and crawl links?

If it's static, then how will manage these links? (we don't have them until we run some JS, or some processing, right?)

**Comment by julieg18** [comment]
> Is Lychee similar to the link checker? In a sense that it can only analyze links that are available statically? Or can it actually render the website and crawl links?

I think it's capable of both, static files and remote websites. But it's unable to find the download links on dvc.org. I think it's due to the fact that the download link dropdown is taken off the html with `js` unless it's opened. I was looking into a way of `lychee` being able to read part of the link and add the base url but no luck so far... But now that you mention `lychee` scanning remote links, we could check the download links that way. We could:
1. Let the link logic stay the way it is, but have the dropdown links be hidden with css instead of taking them off the page with JS.(This also allows screen readers to be able to read the download links as well.)
2. Set up a lychee github action that scans `dvc.org` once a day. We can use a regex flag so that `lychee` only checks the download links.

Anyone see any issues with that idea?

**Comment by shcheklein** [comment]
Sounds good to me. I would also fail if it finds 0 links, or wrong number (that we set in advance as param) links.

Can we trigger it every hour, and may be after redeploy?

**Comment by julieg18** [comment]
> I would also fail if it finds 0 links, or wrong number (that we set in advance as param) links.

Makes sense! Hmmmm `lychee` doesn't seem to support checking the amount of links by default.. But maybe we can find some way to have Github actions read the output, checking the length somehow 🤔 

> Can we trigger it every hour, and may be after redeploy?

Definitely every hour, we just configure one of the Github Action options. As for after redeploy, I'm not sure how we could trigger a Github Action after a Heroku deploy, but there might be a way, I'll need to do some more research 😃

**Comment by rogermparent** [comment]
> I'm not sure how we could trigger a Github Action after a Heroku deploy, but there might be a way, I'll need to do some more research

We do it for link check, specifically with the following snippet:

```
on:
  - deployment
  - deployment_status
jobs:
  run:
    name: Initialize
    runs-on: ubuntu-latest
    if:
      github.event.deployment.ref != 'master' &&
      github.event.deployment_status.state == 'success'
```

A `deployment_status` with `github.event.deployment_status.state == 'success'` indicates that the site is up and ready for requests. `deployment` doesn't work because it only fires when the build starts before the site is up, we have it on link check for a weird hack with the GitHub Checks API, it shouldn't be necessary for this solution.

**Comment by julieg18** [comment]
We now have a check for DVC download links! I'll open a new issue for checking the amount of download links since I wasn't able to get that working.
