### ISSUE TITLE
import: allow "chaining" imports somehow (except circular?)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2610]
> More context around https://discordapp.com/channels/485586884165107732/485596304961962003/676405501940072453

As of now, imported data is not cached by default, so you won't be able to import any imported data:

repo1 -> ✔️ dvc import data -> repo2 🙂 -> ✖️ dvc import data -> repo3 🙁 

Somehow allowing this could be useful for the case where you're building a data registry based on other previous smaller DVC repos, for example. Right now you have to `dvc get` and then `dvc add` those artifacts from scratch in the data registry (so they can be imported in further DVC repos).

Ruslan mentioned something about using "links" to implement this (on [Discord](https://discordapp.com/channels/485586884165107732/485596304961962003/676466989035945984)).

UPDATE: Go to https://github.com/iterative/dvc/issues/3305#issuecomment-836503176

**Comment by dberenbaum** [comment]
Moving to dvc.org since it seems like the remaining work is documentation. 

@jorgeorpinel We might be able to better support https://github.com/iterative/dvc/issues/4527 in the future, but until then it IMO it would be useful to be more clear that imports rely on the original source remote and users need access to that, including for chained imports. Thoughts?

@pmrowla Can you take this one if we need to document it? Is there someone else who should be assigned?

**Comment by pmrowla** [comment]
@dberenbaum I'm guessing it will have to be me since I did the current implementation, you can just assign it to me if/when needed

**Comment by jorgeorpinel** [comment]
Thanks guys, we'll take it over as soon as we have all the basic info.

> running dvc update dir from repo D will only check if dir has changed in repo C

This part may deserve it's own issue in iterative/dvc though?

**Comment by dberenbaum** [comment]
My thoughts: The current behavior could be expected or unexpected depending on the circumstances. There's not a lot of user feedback outside of the one user in https://github.com/iterative/dvc/issues/4527, so I'm not sure it's worth keeping the discussion going. Can we document what we have and revisit if users complain or are confused?

**Comment by pmrowla** [comment]
> > running dvc update dir from repo D will only check if dir has changed in repo C
> 
> This part may deserve it's own issue in iterative/dvc though?

This seems like the expected behavior to me. In this case, I am essentially importing a pinned/frozen stage from repo C. When I run `dvc update` in repo D, I want to check whether or not the frozen stage in repo C has been updated (meaning my final import into D should only be changed if/when someone has run `dvc update` in repo C and `git push`ed that update to repo C).
