### ISSUE TITLE
Improvement of documentation for `tree` command on Windows OS.

### ISSUE THREAD

**Issue by gro1m** [iterative/dvc.org#2611]
Tree command does not work on Windows, should be:
`tree.com .dvc/cache /f`
instead of just
`tree .dvc/cache`

**Comment by jorgeorpinel** [comment]
Hi @gro1m most of our docs use POSIX-like environment terminals (Linux, MacOS). There are tools you can install on Windows to get a POSIX terminal experience, which we list in https://dvc.org/doc/user-guide/running-dvc-on-windows.

Otherwise, yeah unfortunately many of our examples won't work by just copy pasting into Command Prompt. Thanks!
