### ISSUE TITLE
Links to Vega spec are confusing since we use Vega Lite everywhere

### ISSUE THREAD

**Issue by Suor** [iterative/dvc.org#2617]
I passed through by one of such links in plots -> modify -> custom templates section and read into spec for a while before realizing that I shouldn't really bother.

**Comment by shcheklein** [comment]
Example? Could you update them? :)

**Comment by Suor** [comment]
Example is the link in `plots -> modify -> custom templates`. I don't know why we have both links to Vega Lite and to Vega spec, also text goes about spec, so simply updating links will also be wrong.

**Comment by jorgeorpinel** [comment]
Hi. That's actually in the index of the `plots` ref, https://dvc.org/doc/command-reference/plots. The first link (to Vega-Lite) is in the main [description ](https://dvc.org/doc/command-reference/plots#description):

> DVC generates plots as HTML files that can be open with a web browser. These HTML files use [Vega-Lite](https://vega.github.io/vega-lite/). Vega is a declarative grammar...

Then there's a link to the general Vega spec in [Plot templates](https://dvc.org/doc/command-reference/plots#plot-templates) and another one in [Custom templates](https://dvc.org/doc/command-reference/plots#custom-templates). Are you saying it's a totally different thing?

I think the original docs contribution by the core team included both links so that's why we left them, without realizing it may be incorrect. If you could submit a quick update that would be great @Suor, and/or explain what should be linked/why. Thanks!

**Comment by Suor** [comment]
Yes, Vega spec is completely different from Vega Lite, i.e. having different keys in JSON doing same thing in a more elaborate way, i.e. values are also different in format. Reading Vega spec, while having Vega Lite files on a hand is confusing.

**Comment by Suor** [comment]
Thanks for handling this @jorgeorpinel.

**Comment by jorgeorpinel** [comment]
Sure, thanks for the report @Suor
