### ISSUE TITLE
plots: document no-error policy

### ISSUE THREAD

**Issue by pared** [iterative/dvc.org#2734]
In iterative/dvc#5984 we stopped raising exceptions from `show/diff` for `plots/metrics/params/experiments`
Seems that in some cases it might be confusing:
https://discord.com/channels/485586884165107732/485596304961962003/877829757834784768

We should mention that lack of some results is possible if we have problems acquiring the data.

**Comment by TRT-MattB** [comment]
If the exceptions have all turned to warnings instead, I think that is OK. 

I was worried for a moment during debugging my issue that certain warnings had been completely silenced, but I am now pretty confident that most of my problems were due to the use of the Live Server extension to view my html plots. It appears to have been caching an old version of the HTML across multiple sessions.

**Comment by jorgeorpinel** [comment]
Thanks @pared . I assigned you but please lmk if that doesn't work.

**Comment by jorgeorpinel** [comment]
Haven't heard from this confusion again.
