### ISSUE TITLE
Clarify Python parameters behavior

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#2780]
Follow up to https://github.com/iterative/dvc.org/pull/2772.

I have a few additional questions:
* Is there background on why Python parameter support was added (cc @skshetry)? If so, maybe we can explain a typical usage for it in the example? I guess it might be easier to import from a Python file to a Python script than to read from YAML, but I'm not sure I can think of another use.
* Should complex expressions be ignored or raise a warning?
* Should we add a note to https://dvc.org/doc/user-guide/project-structure/pipelines-files#parameter-dependencies?

**Comment by daavoo** [comment]
> Should complex expressions be ignored or raise a warning?

I think that we should start raising a warning, at the very least. In other parameter file formats, an invalid parameter will cause an exception to be raised.

**Comment by jorgeorpinel** [comment]
> background on why Python parameter support was added

I think it was done just since it's native to DVC and a common format in the space. Idk if it's actually used. I've mainly noticed people using yaml and json for this. And if you do have params in a Python file it's probably the same file script used for the stage `cmd` so you probably can't even define it as a params file.

I imagine "typical usage" would be when a project has a separate python config file (common in web frameworks [for example](https://docs.djangoproject.com/en/3.2/topics/settings/) although that's not a good example here of course). Their values may even be loaded from env vars.

> Should complex expressions be ignored or raise a warning?

Raising a warning seems logical except if you're loading a huge script that only has a few globals defined at the beginning and then hundreds or more lines of code. Maybe just raise a single warning irrespective of how many complex expressions are being ignored?

> Should we add a note to https://dvc.org/doc/user-guide/project-structure/pipelines-files#parameter-dependencies?

No need I think. It's already in https://dvc.org/doc/command-reference/params

**Comment by jorgeorpinel** [comment]
> Raising warnings sounds ideal

p.s. this would also be a core issue though. So for this ticket we may have left just improving the motivation and example(s) given?

**Comment by jorgeorpinel** [comment]
@dberenbaum feel free to put tickets that are specifically `C: ref` like this one in your back log, or manage them (mark stale, close, etc.)

**Comment by dberenbaum** [comment]
Sorry, @jorgeorpinel, too many tickets to manage 😓 . Happy to close this as stale. I'll try to take a look at other issues of mine when I have a chance.

**Comment by jorgeorpinel** [comment]
Sorry didn't mean to pressure @dberenbaum . This is not THAT old (< 1 Y). Could keep it open for a few more months too. Up to you

**Comment by dberenbaum** [comment]
No problem at all, thanks for the reminder. Like I said, happy to close this one.
