### ISSUE TITLE
guide: clarify what to do with workspace changes after `exp run`

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc.org#2803]
After running `dvc exp run -n  {EXP-name}`, some "Changes not staged for commit" are generated (i.e. `dvc.lock`, non-cached outputs). 

Running `dvc exp branch {EXP-name} {EXP-branch}` creates a new branch containing those changes, but they are still present in the current workspace.

In order to be able to `git checkout {EXP-branch}`, Iyouneed to somehow manage those changes (i.e. `git add` or `git stash` or `git restore`).

We should recommend to users what to do and potentially add a note commenting that DVC does not handle those not stagged changes automatically (similar to how we comment "Note that DVC **does not** switch into the new branch automatically.)

---

- [ ] What's the recommended method? I guess `git reset --hard` is the simplest approach if you've already captured everything in experiments. That should be enough to clarify.
- [ ] Also note that non-DVC outputs created in queued/temporary experiments are lost (see https://github.com/iterative/dvc.org/issues/2803#issuecomment-916350666).

**Comment by shcheklein** [comment]
What happens if we queue an experiment and run it in the background? do we stage/commit files automatically?

**Comment by jorgeorpinel** [comment]
> In order to be able to git checkout {EXP-branch}, Iyouneed to somehow manage those changes

I think this relates more to `exp run` than `exp branch`. Even if another branch already existed you need to handle your unstaged changes (used by `exp run`) before you can `git checkout`. And for that matter this is a regular part of Git workflow... but I see that it may be a pretty common situation after a series of `exp run`s.

> We should recommend to users what to do

What's the recommended method? I guess `git reset --hard` is the simplest approach if you've already captured everything in experiments. Let's add a checkbox about including that in https://github.com/iterative/dvc.org/issues/2768 ? That should be enough to clarify.

> What happens if we queue an experiment and run it in the background? do we stage/commit files automatically?

@shcheklein there's a trick in which in order to include uncommitted files to queued/tmp experiments you have to stage them with `git add` before `exp run`. `git reset --hard` should also take care of those changes.

_Since its a bit hacky we didn't emphasize this in docs but it's mentioned under the **How are queued experiments isolated? (Temporary directories)** `<details>` section of https://dvc.org/doc/user-guide/experiment-management/running-experiments#running-specific-stages ._

**Comment by shcheklein** [comment]
@jorgeorpinel what happens if a queued experiment produces a new file as it runs?

**Comment by iesahin** [comment]
`dvc exp run --queue` are isolated. e.g.

```
dvc exp run --queue -S param=value1
dvc exp run --queue -S param=value2
dvc exp run --queue -S param=value3
dvc exp run --queue -S param=value4
dvc exp run --run-all
```

doesn't make any changes in the workspace, whereas

```
for v in value1 value2 value3 value4 ; do
   dvc exp run -S param=$v
done
```

leaves the artifacts of the last run in the workspace. (see our discussion with @pmrowla yesterday.) 

The latter are not isolated from each other, for example, if `dvc exp run -S p=v1` changes the workspace so that `dvc exp run -S p=v2` picks up where it takes, we'll have very different behavior from `--queue` or `--temp` of these. 

IMO `dvc exp run` should run the experiment in isolation similar to `dvc exp run --temp`. (It shouldn't move everything to a temp dir, instead stash/reset the repository, run the experiment, and put them later.) Otherwise `--queue`, `--temp` in a loop probably will result in different results than running the experiments directly.

**Comment by daavoo** [comment]
> `dvc exp run --queue` are isolated. e.g.

Are they isolated? https://github.com/iterative/dvc/discussions/6475#discussioncomment-1224321

**Comment by shcheklein** [comment]
I think this issue is not about isolation, unless I'm missing something. This is about artifacts that are produced during the experiment run and if/how we capture them, right?

Still not clear, what happens when I run it in a queue and produces a completely new file that is not DVC-tracked but also not in Git yet. Do we run `git add *` ?

**Comment by daavoo** [comment]
> Still not clear, what happens when I run it in a queue and produces a completely new file that is not DVC-tracked but also not in Git yet. Do we run `git add *` ?

CC @pmrowla which might know better.

From what I have tried, after running `dvc exp run --run-all` the "new files not tracked by DVC" of each queued experiment are not added. Once you run `dvc exp apply {QUEUED_EXP_HASH}` you are in the same situation as the one discussed originally (when running plain `dvc exp run`), you need to deal with not staged changes somehow.

**Comment by dberenbaum** [comment]
> Still not clear, what happens when I run it in a queue and produces a completely new file that is not DVC-tracked but also not in Git yet. Do we run `git add *` ?

As @daavoo said, the short answer is no.

There is a warning, however. See the example below:

```bash
█▓▒░dave@davids-air█▓▒░ Thu Sep 09 02:42:01P
~/repo/ echo "p: 0" > params.yaml
█▓▒░dave@davids-air█▓▒░ Thu Sep 09 02:42:04P
~/repo/ dvc stage add -n foo -p p "cat params.yaml > foo.txt"
Creating 'dvc.yaml'
Adding stage 'foo' in 'dvc.yaml'

To track the changes with git, run:

        git add dvc.yaml
█▓▒░dave@davids-air█▓▒░ Thu Sep 09 02:42:07P
~/repo/ git add params.yaml dvc.yaml
█▓▒░dave@davids-air█▓▒░ Thu Sep 09 02:42:15P
~/repo/ git commit -m "setup exp"
[main 8718d1e] setup exp
 2 files changed, 6 insertions(+)
 create mode 100644 dvc.yaml
 create mode 100644 params.yaml
█▓▒░dave@davids-air█▓▒░ Thu Sep 09 02:42:24P
~/repo/ dvc exp run -S p=1 --queue
Queued experiment 'bf04695' for future execution.
█▓▒░dave@davids-air█▓▒░ Thu Sep 09 02:42:31P
~/repo/ dvc exp run --run-all
Running stage 'foo':
> cat params.yaml > foo.txt
Generating lock file 'dvc.lock'
Updating lock file 'dvc.lock'
WARNING: The following untracked files were present in the experiment directory after reproduction but will not be included in experiment commits:
        foo.txt

Reproduced experiment(s): exp-fa89e
To apply the results of an experiment to your workspace run:

        dvc exp apply <exp>

To promote an experiment to a Git branch run:

        dvc exp branch <exp> <branch>

█▓▒░dave@davids-air█▓▒░ Thu Sep 09 02:42:34P
~/repo/ ls
dvc.yaml    params.yaml
█▓▒░dave@davids-air█▓▒░ Thu Sep 09 02:43:43P
~/repo/ dvc exp apply exp-fa89e
Changes for experiment 'exp-fa89e' have been applied to your current workspace.
█▓▒░dave@davids-air█▓▒░ Thu Sep 09 02:43:52P
~/repo/ ls
dvc.lock    dvc.yaml    params.yaml
```

**Comment by jorgeorpinel** [comment]
> Are they isolated? iterative/dvc#6475 (comment)

They do share the cache (including run-cache). Only their workspaces are isolated. But yeah this isn't about isolation.

Non DVC outputs created in queued/temp experiments being lost also seems like a slightly different topic here but we can expand the ticket to also note about that. I updated the description with 2 check boxes for now but again, I think we could move them to #2768.

**Comment by pmrowla** [comment]
> IMO `dvc exp run` should run the experiment in isolation similar to `dvc exp run --temp`. (It shouldn't move everything to a temp dir, instead stash/reset the repository, run the experiment, and put them later.) Otherwise `--queue`, `--temp` in a loop probably will give different results than running the experiments directly.

This would be easy to implement (this is how experiment execution already works). Currently we skip resetting the workspace after running the experiment, but doing the reset would essentially be a one or two line change.

The reasoning for the existing behavior for workspace runs was:

- It allows have `dvc exp run` to be used as drop-in replacement for `dvc repro`
- When running experiments in my workspace, the expectation was that in the default case, the user is going to want to see the results of the experiment afterwards (so there is no reason to require the user to run an extra `dvc exp apply` command  every time)

---

If we want to change the default behavior, we could add an `--apply` flag to automatically do the apply in the event that users want to see the results in their workspace (without needing the separate `exp apply` command). Or we could keep the existing default and add a `--no-apply` flag for users that don't want the result in their workspace.

**Comment by jorgeorpinel** [comment]
Thanks for the feedback. It's a prod discussion so up to you guys. For now this docs ticket can be addressed by the 2 checkboxes in the description, I think.

**Comment by dberenbaum** [comment]
@daavoo Do you want to keep this one open?
