### ISSUE TITLE
introduce --show-pretty-json into dvc list options

### ISSUE THREAD

**Issue by eggqq007** [iterative/dvc.org#2838]
Currently the dvc list can only output json without formatting.
--show-pretty-json can be add to generate json with pretty formatting and color.

Should update it in dvc.org website doc

**Comment by dberenbaum** [comment]
Hi @eggqq007, thanks for the feature request and PR!

Can you give more context about why you would like this feature?

I ask because if we add `--show-pretty-json` here, we could end up with similar requests for all commands, and I'm not sure whether the benefit outweighs the cost. This is especially true because the same could seemingly be accomplished in other ways (`dvc list --show-json . | jq`). Also, the idea is for `dvc list .` to be human readable and `dvc list --show-json .` to be machine parseable, so I'm wondering why a human readable JSON output is needed.
