### ISSUE TITLE
get started: get rid of local remotes

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc.org#284]
Here: https://dvc.org/doc/get-started/configure

Remote is a complicated concept for newbies. Local remote is even harder to understand. It is better to use S3\SSH or even with no remotes at all.

EDITED: Local remote breaks project shareability - one of the brightest DVC features.

**Comment by shcheklein** [comment]
DVC without remotes is not very useful, right? We have to introduce them one way or another. It's one of the most essential parts - to introduce the concept of sharing and saving your stuff. We can simplify the language, but without them it would be really hard to explain `dvc push`, `dvc pull`.

Local one because get started is made to be run on your local machine, extremely simple steps. We mention explicitly that it's local just to simplify the example and we mention all other supported ones.

I just don't see the way we can avoid remotes, and how can we make it S3 or SSH w/o making the get started effectively not executable within 5 minutes.

@jorgeorpinel @robogeek hey guys, what do you think? what was your first impression of remotes? is there a simple way to simplify it w/o sacrificing the logic?

**Comment by dmpetrov** [comment]
It might look like expanded items with `S3 cloud`\`Azure Cloud`\`SSH Server`\`Local - I don't have any storage`.
In the last option, we should explain that there is no (obvious) value in this remote but you can play with this for training purpose.

**Comment by shcheklein** [comment]
I would not overcomplicate the example - `dvc remote add` command reference describes all the possible ways to setup different storages. We would have to copy 4-5 expandable sections that would distract the attention. That page also mentions S3 at the bottom.

We can def modify the language to mention S3, SSH, etc before local and emphasize even more that in most case local remote does not make much sense and we use it here for simplicity.

**Comment by robogeek** [comment]
The user needs to have some experience with DVC remotes because it is a very useful part of DVC.

Local storage is the simplest to set up and requires no configuration of any remote service.  Every other kind of remote involves some remote service configuration.

**Comment by dmpetrov** [comment]
We definitely should emphasize that local remote is used only for training purpose. The same needs to be specified in https://dvc.org/doc/get-started/share-data and https://dvc.org/doc/get-started/share-data

**Comment by AJ-54** [comment]
@shcheklein Should I add the statement "Local remote is used only for training purpose." at  https://dvc.org/doc/get-started/share-data or there is something more to be done here??

**Comment by jorgeorpinel** [comment]
@dmpetrov @shcheklein sorry just noticed this conversation! One other simple option (to avoid local remotes) is to run a SSH server locally and then use a SSH remote (to localhost) – not sure its less confusing though, maybe just a little.

That's something I tried myself when I was learning for the first time so I know how to run the SSH server on Mac ([easy](http://osxdaily.com/2016/08/16/enable-ssh-mac-command-line/)). Doing so on Linux is also easy (though may depend on distro?). Only for Windows could it be more complicated ([before Win10](https://ittutorials.net/microsoft/windows-10/enable-ssh-windows-10-command-prompt/)).

**Comment by jorgeorpinel** [comment]
Also closely related to this issue, someone noted that the same page (https://dvc.org/doc/get-started/configure) has a command that if ran throws an error:

```console
dvc remote add -d myremote s3://mybucket/myproject
```

(because in the same page a local remote with the same name was previously added. Ivan noted this 2nd command isn't meant to be ran, just an example. I'll address that confusion along with whatever we decide here about local remotes.

**Comment by shcheklein** [comment]
@jorgeorpinel I think running an SSH would complicate too much even on *nix systems. I would stick with local but change wording a little bit like we discussed. I would really love to keep the get started as simple and as fast as possible to try.

**Comment by jorgeorpinel** [comment]
Opened #304 to address the comments above.
