### ISSUE TITLE
Educational Course Connection

### ISSUE THREAD

**Issue by jendefig** [iterative/dvc.org#2955]
With the new educational course coming out at the end of the quarter, we need to determine how people will access it from our websites.  

Each website will access the same school: Iterative Tools School.  

I would like for the school to be accessible  from the navigation and in DVC.org's case, from the Community Page.  

[Here is information on how their domains work](https://support.learnworlds.com/support/solutions/articles/12000080095-general-overview-custom-domains#What-is-a-custom-domain?). Let me know how you think it's best to proceed!

@julieg18 @rogermparent @yalozhkin

**Comment by rogermparent** [comment]
The navigation menu is a bit packed, I'd suggest against adding another top-level item since we already hide items on mid-width screens.

One way we could fit it up there without adding more top-level items is to turn "Support" into a drop-down with the current page under "contact" and the course with a new item under that menu.

Some other good places I can think of:

- A footer link, either in "help" or "community" (help makes more sense, community evens out the items and still makes sense)
![footer screenshot](https://user-images.githubusercontent.com/9111807/138536439-4ef0f23a-f6ba-4553-9da7-bb974bffe948.png)

- Support page "Don't know where to start?" section, next to existing button with another that says something like "Take a Course".
![support page screenshot](https://user-images.githubusercontent.com/9111807/138536160-13a9e199-3ebd-45ec-bf1c-de615c1acf0c.png)

- Docs index page, I'm thinking a CTA between the four nav buttons and the checklist
![docs home screenshot](https://user-images.githubusercontent.com/9111807/138536214-c339976b-c3dd-4f47-b286-e355c7e7a81b.png)

- The "Get Started" doc page that we link to from a ton of places, likely toward the top with an eye-catching CTA.
![get started doc screenshot](https://user-images.githubusercontent.com/9111807/138536276-f1e011c0-0de3-4a31-b2d7-ca269e40c6d0.png)

- Adding it to the alert box on release for a while to drive a big initial boost
![alert box screenshot](https://user-images.githubusercontent.com/9111807/138536544-45a9358f-9f2e-49a0-8495-2597e05388b0.png)

Just some ideas we can pick and choose from, maybe we do a few or maybe we do all of them. I think a link in the "Get Started" doc is one of the most important since it's our existing CTA that I think most users that would benefit from this course will initially be drawn to.

**Comment by julieg18** [comment]
Adding a `p1` label since this course is coming out early next month! 

I tested out attempting to place a "Learn" nav item on our nav bars. Besides mlem.ai, there were issues on different screen sizes. We could technically accomplish it, but we'd have to tweak the nav css again and take off items at different intervals. Not to mention we're already taking items off of dvc.org's nav at different screen sizes, which isn't ideal. We might want to consider a nav refactor to make it easier to add extra nav items 🤔 

We could also just keep the nav bar as is, and implement a link to learn.iterative.ai with one of the ways @rogermparent mentioned! As for the other sites, maybe we could look into adding some kind of banner or popup? 

cc @yalozhkin @iterative/websites @jendefig

**Comment by jorgeorpinel** [comment]
We can link from several places from within docs. 

> Docs index page, I'm thinking a CTA between the four nav buttons and the checklist

Maybe as another checklist item.

> The "Get Started" doc page that we link to from a ton of places, likely toward the top with an eye-catching CTA.

Get Started pages are the most obvious places to link from initially, but as @jendefig docs will be more up to date so maybe from the bottom? The other Q is: do we link to different chapters from each page or just to the general course? I need to catch up with the course development to have a better opinion.

**Comment by jendefig** [comment]
> Maybe as another checklist item.

I think it's logical to be another checklist item, but won't drive much traffic this way.

>The other Q is: do we link to different chapters from each page or just to the general course?
I think the general course.  We risk total confusion and frustration if we try to match from docs to the course.  The reverse is true though.  Pertinent docs for the parts that are covered in the course are in the supplemental materials and will be added to the ebook on a version by version basis.  

@jorgeorpinel We should sync on this.  We need your input.  I know the meeting time is bad for you.  LMK what would work for you. 

Also re @julieg18 comments above.  I'm not understanding what the thumbs up were for because there were a lot of ors and maybes/mights.  

I would love to see it in the navigation.  It signals importance and permanence and will drive the most traffic.  Pop-ups make it seem cheap and temporary.  I would have to see what that looked like.  The modal on the front page is good because it is for temporary things - what's new.  But the courses shouldn't feel like that.  Should be more permanent.

What if Docs, Blog and Learn were under a 'Resources' navigation?

**Comment by shcheklein** [comment]
My 2cs. For the tool websites (DVC, CML, MLEM, etc) - we should keep Docs as a top level link. This is one of the most common things people are looking for.

If we keep it in the nav bar how do we plan to name it - "Learn"? Will users understand from the nav bar where does it lead - that this is about courses?

**Comment by julieg18** [comment]
Looked into ways to update our nav bars design! 

I looked at other nav bars that have a lot of items. They seem to solve the problem in two different ways:

1. The nav item text is a lot smaller, allowing room to fit a lot more items.
2. They have a `...` or something similiar that opens up a dropdown that holds the rest of the items on smaller screen sizes. 
3. They group items into dropdowns

I looked into (3) but we don't have that many items on our nav bars and I couldn't think of ways to group them that would make sense. (2) doesn't seem to be that commonly used. I could only find [one example of (2) on bing](https://www.bing.com/), so (1) might be the best option. Quick example of how (1) could look: 

![image](https://user-images.githubusercontent.com/43496356/151451741-cfe2ed17-ec05-4cb4-9ba8-7ace7707ca65.png)

What do you think? cc @iterative/websites, @yalozhkin

**Comment by shcheklein** [comment]
2 sounds good to me, I would put Features there and make Learn go after Doc ... Blog could also go at the end

**Comment by yathomasi** [comment]
I think we can approach a mix of 2 and 3. We can have ... at the end and have a single dropdown which will have grouped items like `Community`, `Other tools` as well as simple items like `Features`. And, the nav items with higher priorities can be on the navbar itself. I think this will be scalable as well if we want to add a new nav item we now at least know a place.

We can check how it looks on the design too. @yalozhkin wdyt?

**Comment by jendefig** [comment]
Just out of curiosity, why is Features not just on the main page?

**Comment by rogermparent** [comment]
> 2. They have a `...` or something similiar that opens up a dropdown that holds the rest of the items on smaller screen sizes.

> 2 sounds good to me, I would put Features there and make Learn go after Doc ... Blog could also go at the end

We could adapt our current mobile burger menu to be able to appear on slightly larger screen sizes where the "..." would be, probably fixed on the right side with a limited width. This way, we can reuse a menu view we already have instead of adding a third whole new representation of the navbar.

**Comment by julieg18** [comment]
> We could adapt our current mobile burger menu to be able to appear on slightly larger screen sizes where the "..." would be, probably fixed on the right side with a limited width. This way, we can reuse a menu view we already have instead of adding a third whole new representation of the navbar.

Good idea about reusing the menu we already have! The only con I can think of is that a user would have to make an extra click to get to main menu links like Docs... @iterative/websites, do we have a preference between these two ideas?

Quick examples of how both would like at around tablet size:

![image](https://user-images.githubusercontent.com/43496356/151874750-bef4ec52-c61a-424f-9437-98b12e586389.png)

![image](https://user-images.githubusercontent.com/43496356/151875262-781886b1-d59c-4fbb-9fbb-041544827527.png)

**Comment by jendefig** [comment]
Interesting.  I think there's an expectation for having some kind of navigation at the top and Doc should be there for sure if so (parenthetical why do we use "Doc" instead of "Docs" which is more customary @jorgeorpinel?).  

That being said, the clean look is nice and directs the eye to the Studio banner I think more than when having the Navigation is there, but that isn't what should be our first focus for this.  

What if the Get Started button were next to DVC by iterative.ai and then the hamburger button all the way to the right.  So when you arrive at the page it's like, "TL;DR Get Started" and if you want more info, everyone knows it's in the hamburger?

**Comment by julieg18** [comment]
After some discussion with Ivan, we've decided we're going to go ahead and make the fonts a little smaller and add a `...` dropdown for now to fit the new nav item (`...` instead of hamburger menu since only dvc.org has a hamburger menu).

We definitely want to consider nav bar refactors for all sites (make navs more similiar, prioritze certain items better, etc.) in the future but the `...` should suffice for resolving this issue and meeting the deadline :)

**Comment by jorgeorpinel** [comment]
> parenthetical why do we use "Doc" instead of "Docs" which is more customary @jorgeorpinel

Old discussion, not sure where it is anymore. I remember that I argued for "docs" but lost the vote.

**Comment by jorgeorpinel** [comment]
But also doing some research back then we did not find that one was more customary than the other.

**Comment by jorgeorpinel** [comment]
> Just out of curiosity, why is Features not just on the main page?
 
Yeah we have been considering what to do with Features for a long time, we should get to that whole home page + basic nav redesign this quarter (it's in my to-dos to drive that).

> consider nav bar refactors for all sites

For the record, 2 things I'm looking into as possible follow-ups (including that):

- Links from cml.dev and studio.iterative.ai ? Maybe from DVCLive docs or its repo README, even (for that matter other repo READMEs as well).
- Review/add links from specific course pages to certain docs (all products)
