### ISSUE TITLE
ref: consistent cmd alias strategy

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc.org#2989]
**Current CLI aliases**
> Bugs marked with check boxes 🐞 

- [version](https://dvc.org/doc/command-reference/version)-> [doctor](https://dvc.org/doc/command-reference/doctor): the former **doesn't** mention the latter; The latter has it's own short page linking to the former (not great).
  > - [x] There are no links to either one from any other refs or guides. There should be some at least.

- [list](https://dvc.org/doc/command-reference/list) -> ls: the former mentions the `ls` alias; ~~The latter [doesn't exist](https://dvc.org/doc/command-reference/ls).~~
  > - [ ] Other docs link to `list` only ATM. Update?
  > - [x] `ls` not existing seems like a bug ATM (quite inconsisntent)

- [experiments](https://dvc.org/doc/command-reference/experments) -> [exp](https://dvc.org/doc/command-reference/exp): ~~The former doesn't exist;~~ Only the latter (the alias) is on the cmd ref nav.
  > - [x] `experments` not existing is a bug -- as it used to be the path, it should be redirecting to `exp`.
  > - [x] Also, the now `exp` page says it's "aliased to `exp`" which no longer makes sense.

**Solution**

Let's pick which name is considered most important, whether original or alias (I vote for `version`, `ls`, `exp`) and only have that on the nav (and terminal block highlighter?). WDYT @dberenbaum ?

Questions:

- Do we even mention the alternative name in docs?
- [ ] We should also review what the `-h` help output is doing for these, probably (Core DVC question)

**Also...**

We sometimes call the special `remote://` remote URL format a "remote alias". Should probably use this term consistently or remove it altogether.

UPDATE: Some decisions in https://github.com/iterative/dvc.org/issues/2989#issuecomment-966546066 below

**Comment by jorgeorpinel** [comment]
Related product question @dberenbaum @efiop : should `exp list` and other listing commands have `ls` aliases too? Thanks

**Comment by dberenbaum** [comment]
TBH I'm not sure what the motivation was for each of these aliases (except for `exp` which is obviously just shorter). @efiop any reason why we developed these aliases?

I would probably lea

> Let's pick which name is considered most important, whether original or alias (I vote for `version`, `ls`, `exp`) and only have that on the nav (and terminal block highlighter?). WDYT @dberenbaum ?

Sounds good.

>     * Do we even mention the alternative name in docs?

I don't think we need to.

>     * Should we also review what the `-h` help output is doing for these? (Core DVC question)

Sure, we can do that as a follow-up.

> Related product question @dberenbaum @efiop : should `exp list` and other listing commands have `ls` aliases too?

Hm, maybe that's a reason to keep `list` instead of `ls` for more consistency. I don't think `ls` makes as much sense for commands that don't return filesystem-like output.

**Comment by efiop** [comment]
> version-> doctor: the former doesn't mention the latter; The latter has it's own short page linking to the former (not great).

Can just introduce a redirect, that should be enough. `doctor` is a successor to `version`, because people were confusing it with `--version`. We use `doctor` when talking with users these days.

> list -> ls: the former mentions the ls alias; The latter doesn't exist.

Good catch, looks like we forgot to add a redirection for dvc.org. https://github.com/iterative/dvc/pull/6683

> Do we even mention the alternative name in docs?

I would say that redirections are enough, no need to elaborate on aliases, main cmd name is enough.

> Should we also review what the -h help output is doing for these? (Core DVC question)

`-h` just shows the main name (e.g. list for `dvc ls -h`)

> We sometimes call the special remote:// remote URL format a "remote alias". Should probably use this term consistently or remove it altogether.

This is an advanced feature that will likely change in the future. I would probably just ignore it for now, no reason to spend time on it. Btw, don't really remember `remote alias`, i use `remote notation` usually.

**Comment by jorgeorpinel** [comment]
> I would probably lea

@dberenbaum seems like that sentence was cut off somehow, were you proposing something?

**Comment by jorgeorpinel** [comment]
> `exp` which is obviously just shorter

Sounds like we all agree `exp` is the better form.

> keep list instead of ls for more consistency

Agree. Going with `list` for now in docs. Should we make a core issue to roll back the command name?

> We use `doctor` when talking with users

OK `doctor` it is then (`version` won't be shown in docs).

> redirections are enough

Agree but some of the current redirects may be 301 (permanent) accidentally so we need to be careful not to change that in a way that generates redirect loops...

**Comment by dberenbaum** [comment]
> > I would probably lea
> 
> @dberenbaum seems like that sentence was cut off somehow, were you proposing something?

Not sure. I probably started to write something and decided to reply directly to quotes instead.
