### ISSUE TITLE
start: pipelines video doesn't match latest code

### ISSUE THREAD

**Issue by skailasa** [iterative/dvc.org#3055]
From this https://dvc.org/doc/start/data-pipelines, the youtube video uses the param `train.n_estimators` (around 6:20) whereas the code downloaded for this example has `train.n_est` in its params.yml file.

**Comment by jendefig** [comment]
Thanks for pointing this out @skailasa!  We are working on a resolution!

**Comment by jorgeorpinel** [comment]
What's the plan @jendefig ? I guess it wasn't a great idea to call out specific docs commands in the video since the docs tend to change and evolve (as well as example projects cc @iesahin).

Also is it a huge deal since `train.n_estimators` and `train.n_est` are similar enough that hopefully it's obvious to users which one to use? Not sure, but if it's not a big deal we can add a note above videos or overlay on videos (Youtube has that feature) with a note that the code example has changed slightly.

**Comment by jendefig** [comment]
Yes.  I think that's what is certainly the most expedient and clarifying.

**Comment by jendefig** [comment]
The video now has a subtitle that directs how to correct the code at 6:34 and 7:30 now. 🎥 🎉 

Thanks again @skailasa for the callout!

**Comment by jorgeorpinel** [comment]
Nice 👍
