### ISSUE TITLE
Update `dvctable` style

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc.org#3102]
To match https://github.com/iterative/dvc/pull/7142 ~~(when merged)~~

- [ ] Alternating background color in rows
- [ ] Use rich `box.HORIZONTALS` style (https://rich.readthedocs.io/en/stable/appendix/box.html)

<img width="766" alt="Captura de pantalla 2021-12-14 a las 18 12 55" src="https://user-images.githubusercontent.com/12677733/146046813-869327d8-fe49-411c-b183-9025dda9c5c9.png">

**Comment by daavoo** [comment]
Not sure if it can be considered a priority but in #3112 I had to patch my local branch reverting iterative/dvc#7142 in order to be able to generate tables for the docs. 

Syntax highlighting doesn't work with the `box.HORIZONTALS` output and manually creating/editing tables seemed inefficient.

**Comment by iesahin** [comment]
How are you generating the docs tables from `dvc exp show` output? @daavoo

**Comment by daavoo** [comment]
> How are you generating the docs tables from `dvc exp show` output? @daavoo

Copy-paste from terminal output

**Comment by iesahin** [comment]
probably you also get the control codes, right? what's the output you paste?

**Comment by julieg18** [comment]
Using `prismjs`, here is what I've been able to do so far: 

![image](https://user-images.githubusercontent.com/43496356/147511500-d476fcef-307b-4000-9a41-173a895062e4.png)

The only thing I couldn't figure out how to do was coloring the header cells. We can use regex and our already made `dvctable` methods to color the header text itself. But since the new design has no lines in between the header columns, there isn't a way to figure out where a cell starts/stops with just regex. Though if we think this is good enough, we could merge this for a first iteration 🤔 cc @iterative/websites

**Comment by shcheklein** [comment]
Looks great @julieg18 ! I think we can go ahead and merge it like this.

**Comment by daavoo** [comment]
Sorry for the inconvenience @julieg18 🙏  

It looks like we might leave the default as it previously on DVC and alternating rows will only be enabled via `dvc config` option. 

So, we could leave the tables with the current style

**Comment by iesahin** [comment]
I believe we can keep the alternating row colors even if it requires a config option. If users ask how to show the table as in the docs, we can point to the option.

**Comment by julieg18** [comment]
> So, we could leave the tables with the currently deployed style, unless you prefer to merge the alternating rows. I personally prefer the current style with header color expanding the hole cell)

> I believe we can keep the alternating row colors even if it requires a config option. If users ask how to show the table as in the docs, we can point to the option.

I personally think we should keep the old design since all of our tables across the site are already using it, giving us less work to do to keep all tables consistent. And it makes sense to me that we show the default table in the docs, especially in the "Get Started" sections.  But I could still open a pull request for adding the new table style as an option. Maybe `dvctable-horizontals`?

**Comment by shcheklein** [comment]
@daavoo do we change borders though?

**Comment by julieg18** [comment]
We now have `dvctablehorizontals` (opening a pr to change this to `dvctable` today)!
