### ISSUE TITLE
Support "Click to expand" for images.

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc.org#3131]
I think it would be nice to have a button to expand images to full size without losing the context (currently, clicking leaves you to a new tab). 

Something like https://codyhouse.co/demo/expandable-image-gallery/index.html#0

**Comment by jorgeorpinel** [comment]
Idk. I like the new tab. I can just Ctrl + W it instead of finding some x icon to go back to the content. I guess it's a minimal difference, exp. if something like Esc can be used to close it. But in general I'm not sure I understand the value of this feature out there, except for actual galleries.

**Comment by shcheklein** [comment]
I think there are two things here from the product perspective - first, we could make images a bit responsive so that it's visible that they could be expanded.

Second is the UI itself on how to expand them. 

On the second, we should probably do popup or a separate tab to avoid messing up with the docs layout.

**Comment by jorgeorpinel** [comment]
On the latter, it's a separate tab already. Simple but it does the trick, plus you get the source URL directly in the address bar.
