### ISSUE TITLE
npm package is incompatible with nodejs 17

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc.org#3204]
The docs/website npm package is currently pinned to nodejs <= 16, the latest version of nodejs is 17.4.0, and anyone using node installed from homebrew on macos will have 17.x

https://github.com/iterative/dvc.org/blob/d29478ec6d846747b4a48eb76154dacae1af75ca/package.json#L36-L38

```
$ yarn
yarn install v1.22.17
[1/5] 🔍  Validating package.json...
error website@1.0.0: The engine "node" is incompatible with this module. Expected version ">=14.x <=16.x". Got "17.4.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I'm not sure if the version is pinned for a specific reason, but as far as I can tell unpinning it to allow 17.x works for me (at least for making docs/cmd related PRs)

**Comment by rogermparent** [comment]
I had been working locally with Node 17 manually, and while it mostly works I've encountered a Node 17 specific error: when building, there's many instances of an error along the lines of "Possible memory leak detected, 11 listeners attached to PassThrough"- While it says error, it's more a warning since the site works.

The initial motivation for setting a max version is because an automatic Heroku update broke site builds back when we were on Gatsby 2, which was incompatible with Node 16+.

While I think Node 17 works fine enough for local development, if we allow it we'll have to ensure Heroku doesn't automatically go up like last time.

**Comment by pmrowla** [comment]
I just noticed that the "use an LTS release" requirement is documented, so it sounds like this is expected behavior.

**Comment by jorgeorpinel** [comment]
I've fallen for this confusion several times 😅
