### ISSUE TITLE
investigate: check that if algolia integration fails it does not get the whole site down

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc.org#369]
More context:

https://twitter.com/bob4mob/status/1130100767082328064

**Comment by shcheklein** [comment]
Partially fixed by @algomaster99 

Need to investigate if there is a better way to pull the Algolia? NPM package?

**Comment by algomaster99** [comment]
@shcheklein 
![Screenshot from 2019-07-16 09-43-52](https://user-images.githubusercontent.com/35191225/61265542-3feaa080-a7ae-11e9-94dd-94f77cb632ba.png)

The user means that he saw these errors in the console. This is happening since it failed to fetch content from the CDN links. I think he means these statements as an unexpected error otherwise it's working fine.

Also, an [NPM package](https://www.npmjs.com/package/docsearch.js) is also available as an alternative and we should switch to it.

**Comment by algomaster99** [comment]
@shcheklein I suggest that we can get rid of the `HeadInjector.js` since all of the CDN links are available as NPM packages:
- [GitHub markdown CSS](https://www.npmjs.com/package/github-markdown-css)
- [Perfect Scrollbar](https://www.npmjs.com/package/perfect-scrollbar)
- [docsearch](https://www.npmjs.com/package/docsearch.js)

**Comment by shcheklein** [comment]
yep, the only reason I see behind using CDN is that it can be faster. I would check if algolia is large enough and it can be an issue. Not sure about other two libraries.

**Comment by algomaster99** [comment]
@shcheklein using [this site](https://bundlephobia.com/), you can find how these packages will affect the bundle.
- docsearch.js: 35.4kB
- github-markdown-css: 4.4kB
- perfect-scrollbar: 5.1kB

These sizes are according to the production environment since the packages are zipped and bundled.

**Comment by shcheklein** [comment]
so, all of them except for `docsearch.js` are CSS files being injected. Probably, this is the way to do this for those packages. `docsearch.js` - let's do some research, what is the recommended way on the Algolia website to connect their JS? Is it only about the size?

**Comment by algomaster99** [comment]
@shcheklein I couldn't find if they recommend a specific way. I think both are fine.

**Comment by shcheklein** [comment]
Sounds good! k, let's try to migrate docsearch and we can remove the workaround you introduced then.

**Comment by algomaster99** [comment]
@shcheklein It is not working somehow.
I ran `npm install --save docsearch.js` and imported it as `import docsearch from 'docsearch.js'`
It throws the followig error:

```
window is not defined
ReferenceError: window is not defined
    at Object.<anonymous> (/home/poski/gsod/dvc.org/node_modules/autocomplete.js/zepto.js:5:119)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/poski/gsod/dvc.org/node_modules/autocomplete.js/src/standalone/index.js:4:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

And sometimes when it loads, the CSS for it is missing and there isn't any separate NPM package for enabling CSS for it.

**Comment by shcheklein** [comment]
@algomaster99 k, closing this then. Let's keep it guarded. What about your region, does it work for you now?
