### ISSUE TITLE
plots: add bar_horizontal and bar_horizontal_sorted templates

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc.org#3953]
### Report

@tibor-mach @pared Would one of you mind adding these new templates to the docs? Thanks!

**Comment by tibor-mach** [comment]
I can do that...but dunno how to contribute to the docs :-)

**Comment by tibor-mach** [comment]
You don't use Sphinx, right?

**Comment by pared** [comment]
@tibor-mach 
we are using this repository, adding those templates would require changing the pages responsible for examples:
`content/docs/command-reference/plots/show.md` and including those templates in:
`content/docs/user-guide/visualizing-plots.md`
If you want to try, we can help you iterate on that. Its basically editing markdown files. :)

**Comment by dberenbaum** [comment]
Thanks @tibor-mach! You can also take a look at https://dvc.org/doc/contributing/docs.

**Comment by tibor-mach** [comment]
PR ready. Just out of curiosity - why don't you use Sphinx (given that dvc is entirely in python and sphinx can work stuff like doctests which are useful to keep documentation up to date)? 

Not to say that you do it wrong, I'm just curious about why you opted for the setup you have :-)

**Comment by pared** [comment]
Regretfully I am unable to answer this question, @shcheklein @jorgeorpinel ?

**Comment by jorgeorpinel** [comment]
Hi. Just for the record, when was this introduced, was it in https://github.com/iterative/dvc/pull/8282 ? Thanks

**Comment by jorgeorpinel** [comment]
p.s. what about vertical bar charts? I had the impression those were also available.

**Comment by jorgeorpinel** [comment]
> why don't you use Sphinx

@tibor-mach we are considering automating some of the command references but most of our docs are not connected to docstrings directly.

**Comment by tibor-mach** [comment]
@jorgeorpinel no, it was [here](https://github.com/iterative/dvc-render/issues/8)

@jorgeorpinel We had a discussion about the plot options in general. It is very easy to make plots vertical as well, or to make them vertical and sorted or ... the problem is that you can then quickly end up with so many vega templates that have practically the same code (with a single line being different). Of course, I am not a part of your team, so not my call, but personally I'd consider a "feature freeze" on the templates and try to come up with a way to make plots more "modular" than with static templates...

Of course, the question is whether that makes sense, since you might just end up redressing the vega syntax. But it would make a lot of sense from the user's perspective to have something like a bar_plot and then optional parameters which modify it slightly (sorting, vertical vs horizontal etc). I guess you could do that with having something like a BaseBarPlot and using inheritance which could potentially also keep the code a bit more DRY.

Anyway, it is not my call :-)

As for Sphinx, I guess it really shines the most with auto-generation of documentation but I also use it to manually write pages in the tutorial or user-guide style (it supports both reStructuredText and with some plugins also markdown, or MyST). I guess that for me the most attractive thing is that I can use it to generate a pretty and well-organized website without me having to bother with any real front end development or even knowing any javascript. But I guess that since you have fullstack devs, your approach can give you more flexibility in the design than Sphinx could offer (without having to maintain your own Sphinx templates).

**Comment by jorgeorpinel** [comment]
Thanks for the context!

And yes we even have an entire [Gatsby](https://www.gatsbyjs.com/) [theme](https://www.gatsbyjs.com/docs/themes/) which serves as our docs engine and we may one day publish for other people to use (if you're interested lmk to try getting you beta access 🙂)
