### ISSUE TITLE
Experiments: new behavior for exp names

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc.org#4176]
Changes to cover behavior introduced in https://github.com/iterative/dvc/pull/8659

**Comment by jorgeorpinel** [comment]
Do you think https://dvc.org/doc/start/experiment-management/experiments needs an update? There's a `exp show` table with some exp IDs and this one phrase:

> We can see that the experiment we ran has a name exp-ff24d and was run from the commit ID 999710f.

Otherwise there's this guide section: https://dvc.org/doc/user-guide/experiment-management/experiments-overview#how-does-dvc-track-experiments
And a bunch of mentions of exp names in https://dvc.org/doc/user-guide/experiment-management/comparing-experiments.

In the cmd ref there are some definitions around exp names such as https://dvc.org/doc/command-reference/exp/run#-n as well as in other pages.
