### ISSUE TITLE
describe config/remote `--local` option and implications of not using it

### ISSUE THREAD

**Issue by casparjespersen** [iterative/dvc.org#469]
Currently, the effect of assigning a connection string to an (Azure) remote is, that the `.dvc/config` file is updated with the actual connection string. This means that it will be exposed to Git, which is unlucky if you care about your data security.

I would suggest a fix where dvc automatically searches for the connection string in an environment variable (or a .env-file, or similar), e.g. `DVC_REMOTE_{NAME}`. This makes it more secure, and would also allow it to work with modern CI tools.

**Comment by casparjespersen** [comment]
Sure. It looks like a really interesting project, looking forward to trying it out!

**Comment by shcheklein** [comment]
@efiop ideally we should be detecting when someone is trying to use `dvc remote modify` to save something into the project's config. So, it looks like it's not only about docs.

@casparjespersen since you are familiar with Azure, would be great if you can edit the remote add, remote modify command references? You can just click the Edit on Github button and put the note online :)

**Comment by efiop** [comment]
@shcheklein We could do that, but I don't think it is worth the effort to set up notifications for particular remote parameters. It would only complicate the internal logic for matters that are common sense.
