### ISSUE TITLE
get started: wrong md5 of the data.xml

### ISSUE THREAD

**Issue by dniku** [iterative/dvc.org#529]
(dvc version and other environment details are probably irrelevant)

https://dvc.org/doc/get-started/add-files suggests that the MD5 hash of [`data.xml`](https://dvc.org/s3/get-started/data.xml) is `a304afb96060aad90176268345e10355`, but it is actually not:

```bash
$ md5sum data.xml
a86ca87250ed8e54a9e2e8d6d34c252e  data.xml
```

However, `.dvc/cache` still contains `a3/04afb96060aad90176268345e10355`. Perhaps a footnote explanation of the discrepancy would help improve the documentation?

**Comment by shcheklein** [comment]
Most likely:

Related: https://github.com/iterative/dvc.org/issues/68 . 
Related: https://github.com/iterative/dvc/issues/992

@dniku to give a bit more context. DVC is doing dos2unix normalization before running md5 on the file. This is why you see this discrepancy. 

We were hesitant to document the way it's calculated now because we want to remove this normalization in the future, but it looks like it's better to put a section somewhere that describes it.

**Comment by dniku** [comment]
Thank you for a prompt comment. I suppose this issue should be closed, as it duplicates https://github.com/iterative/dvc.org/issues/68.
