### ISSUE TITLE
simplify get-started by removing references/links to advanced doc pages

### ISSUE THREAD

**Issue by dashohoxha** [iterative/dvc.org#545]
After finishing the “Get Started” tutorial, I have a feeling that it is a bit more complex than it should be for a beginner. For example the links and references to more advanced and complex explanations only distract the reader and are not much useful.

My opinion is that a good first tutorial should be consistent, self-contained and sequential (reading it from the beginning to the end, like an article, without jumping forth and back to more advanced doc pages). If there is something that needs to be explained, it is much better to include a paragraph or a note to the text of the tutorial itself, instead of sending the reader to another page (“for more details click here”).

For example what is the point or benefit of referring the reader to a future chapter/section of the tutorial itself, when the reader will eventually get there if he just reads in order. (However it makes sense to refer back to past sections of the tutorial, to remind the reader something, if necessary).

So, my opinion is that Get Started may need to be simplified a bit.

**Comment by shcheklein** [comment]
Agreed. The initial idea was to keep as simple as possible. But it has been growing with more and more details over the time. @dashohoxha it would be great to put a list of things you think can be simplified/removed so that we can discuss.

**Comment by dashohoxha** [comment]
> @dashohoxha it would be great to put a list of things you think can be simplified/removed so that we can discuss.

Can I work on simplifying/improving it instead? The things that I will try to do:
- Move detailed installation instructions on a dedicated page (under User Guide).
- Remove references to more advanced docs or pages. Maybe simplify any explanations too.
- Put links to the interactive lessons (https://katacoda.com/dvc/courses/get-started).
- However this can be properly done if the structure is changed a bit. Also 16 sections are too much, I will try to reduce them to 8 (using subsections if needed).
- etc.

**Comment by shcheklein** [comment]
@dashohoxha 

> Move detailed installation instructions on a dedicated page (under User Guide).

Yep.

> Remove references to more advanced docs or pages. Maybe simplify any explanations too.

Can you give some examples? I would say it depends. Like in the previous case - I think even if we move stuff out, it would makes sense to keep a link to the User Guide page.

> Put links to the interactive lessons (https://katacoda.com/dvc/courses/get-started).

Good. May be let's decide on when we have a run on Katacoda button? I think it'll solve this problem.

> However this can be properly done if the structure is changed a bit. Also 16 sections are too much, I will try to reduce them to 8 (using subsections if needed).

I think it can be done, but I don't see any clear benefits of changing the structure. Not a major get started problem for sure. The whole point was to keep these sections one screen long. One command per section. For the very fast skimming through them. W/o even a need to run anything ideally at all and still being able to get the idea of DVC (and if needed go and read advanced stuff).

> etc.

My overall take on this:

- Improving Used Guide is a bigger priority than this. One reason - even to start with Install you need a page in the User Guide. Some things could be done in parallel.
- If we go with this - do this step - by step. One section each PR, so that we can discuss and give feedback in advance.

**Comment by dashohoxha** [comment]
I am starting with the installation page only, since this is definitely desirable.
For the rest it seems that there is no agreement or clear idea of what needs to be done.

**Comment by shcheklein** [comment]
yeah, but let's keep this ticket open even after we merge the Install refactoring.

**Comment by dashohoxha** [comment]
>  let's keep this ticket open even after we merge the Install refactoring

Sure. I did not intend to close it.

**Comment by dashohoxha** [comment]
I believe this issue can be closed in favor of this one: https://github.com/iterative/dvc.org/issues/599
