### ISSUE TITLE
remove deprecated lifecycle methods from React components

### ISSUE THREAD

**Issue by iAdramelk** [iterative/dvc.org#584]
Starting from React 16.3.0 some lifecycle methods are considered deprecated and will be removed in React 17.0.0: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

There is now 2 component that using deprecated methods:

- `src/GithubLine/index.js`
- `src/Layout/index.js`

They it should be rewritten without it.

**Comment by jorgeorpinel** [comment]
> will be removed in React 17.0.0

To be precise, the old method names will be removed but we're already using the new ones, [UNSAFE_componentWillMount](https://reactjs.org/docs/react-component.html#unsafe_componentwillmount) and [UNSAFE_componentWillReceiveProps](https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops). We should still remove them though, since they are considered unsafe. Here's their current usage:

https://github.com/iterative/dvc.org/blob/a70c8d44f0d83933b5ee8b6a3b582500f9fe0630/src/GithubLine/index.js#L9-L18

https://github.com/iterative/dvc.org/blob/a70c8d44f0d83933b5ee8b6a3b582500f9fe0630/src/Layout/index.js#L12-L24

**Comment by shcheklein** [comment]
Probably not relevant anymore @pavelgrinchenko ?

**Comment by pavelgrinchenko** [comment]
Yep. Seems it was refactored when Alexey migrated website to Gatsby
