### ISSUE TITLE
docs: update sample dvc command outputs

### ISSUE THREAD

**Issue by Suor** [iterative/dvc.org#614]
These things in example output are no longer printed out by `dvc`:
- "`Reproducing '<dvc-filename>'...`"
- "`Using '<dvc-filename>' as a stage file`"

The first one was simply removed in [this commit](https://github.com/iterative/dvc/pull/2440/commits/c68b76f8434ac20f937696421e9a5315475d0085). Not sure what is the story behind the second one.

**Comment by jorgeorpinel** [comment]
Another one: #551

**Comment by VANRao-Stack** [comment]
Where in the docs are these sample outputs? I found the one for reproduce here, https://dvc.org/doc/tutorials/get-started/reproduce#reproduce, however the issue seems to have already been resolved.

**Comment by jorgeorpinel** [comment]
Hi @VANRao-Stack thanks for finding this issue in the context of GSoD. "sample command outputs" refers to all the sample commands in many of our docs, for example the block reading `$ dvc checkout` here:

![image](https://user-images.githubusercontent.com/1477535/82291950-83361280-996f-11ea-8e8d-c6ad63d37a24.png)
> From https://dvc.org/doc/command-reference/fetch

To find where the strings mentioned in the description are found, you could simply clone the repo and find them from your IDE. BTW, this issue may be outdated and I wouldn't be surprised if they're already gone. If you can't find them please lmk and we'll probably close this one 🙂 otherwise you could submit a PR updating them to what the latest DVC version actually outputs (for this you may have to install DVC actually run the commands). Please contact me if you have more questions.

**Comment by shcheklein** [comment]
Let's do this as we go.
