### ISSUE TITLE
git-annex faq appears to be incorrect

### ISSUE THREAD

**Issue by aragilar** [iterative/dvc.org#63]
I'm not sure the comparison to git annex is correct. For example "Git-annex loses all metadata when shared by Git server" isn't true, as it is possible to move files around via special remotes, and store the metadata on git-only servers (datalad, which wraps git annex, shows an example of doing this exact thing).

**Comment by dmpetrov** [comment]
@aragilar  thank you for noticing that!
This comparison  is very short and not exactly correct. I've tried to clarify that. Please take a look:

Git-annex is data file centric-system where DVC is an ML workflow-centric. When a project is cloned by git clone data files won't be cloned (for both DVC and Git-annex) because files content is stored in a separate data remotes . However, DVC metafiles will be cloned correctly from any Git server and ML workflow can be easily reproduced with another data files.

**Comment by aragilar** [comment]
A slightly reworded version:
Git-annex is a datafile-centric system whereas DVC is focused on providing a workflow for machine learning and reproducible research. When a DVC or Git-annex repository is cloned via git clone, data files won't be copied to the local machine as file content is stored in separate data remotes. However, DVC metafiles (which provide the reproducible workflow) are always included in the cloned Git repository and hence can be recreated locally with minimal effort.

**Comment by aragilar** [comment]
Something else worth mentioning in the FAQ: I got the impression (which may be wrong) that dvc isn't fundamentally bound to git, having the option of changing the repository format (when something better than git is created) would be worth mentioning (both git annex and git lfs seem to be strongly coupled to git and git's internals).

**Comment by shcheklein** [comment]
@aragilar Thank you! Would you mind creating a PR for the documentation? there is an "Edit with Github" button on top of each page. You absolutely correct about git+dvc relationship. And it's not only because we are waiting for something better, it's also about an ability to run it on top of Hg, for example. If you see a good place for this information on that page, please feel free to put it there.

**Comment by shcheklein** [comment]
Made the change, including a note that DVC is not fundamentally bound to Git.

**Comment by aragilar** [comment]
Sorry, been really busy and so this dropped off my todo list. The changes look good!
