### ISSUE TITLE
"Edit on GitHub" button blindness

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc.org#684]
I heard from a couple of potential docs contributors that they have not noticed "Edit on GitHub" button on the docs web site.

One guy simply didn't contribute because of that. Another guy started contributing in a regular way - by cloning the repository.

1. It might be helpful to make the button more visible.
2. Contribution in a regular way should work (heard another concern about it).

**Comment by gagejustins** [comment]
(that guy is me)

**Comment by algomaster99** [comment]
> 2\. Contribution in a regular way should work (heard another concern about it).

What does this mean?

Also, I have two suggestions to show it.
### 1
Have a fixed ribbon like this for forking.
![Screenshot from 2019-10-10 02-00-02](https://user-images.githubusercontent.com/35191225/66517946-b07d3100-eb01-11e9-986f-22bd5131e735.png)


### 2
Edit it directly.
![Screenshot from 2019-10-10 01-54-20](https://user-images.githubusercontent.com/35191225/66517525-e7067c00-eb00-11e9-8233-37eceb75cf84.png)

**Comment by shcheklein** [comment]
Tbh, I think people are just not familiar with the concept of editing the docs in the first place on Github. They just don't expect to see the button here. The only way to optimize it would be either highlighting it significantly or using pop ups. The downside of this - we are distracting our readers from the content - the main reason the come to the site. Let me try to introduce some emoji symbols to the text around both buttons, otherwise I don't we should do more than what we have already.

**Comment by jorgeorpinel** [comment]
Agee it's pretty visible once you pay attention to the sidebar.

> 2. Contribution in a regular way should work (heard another concern about it).

What was the concern here? Contributing via forking as explained in our [contrib docs](https://dvc.org/doc/user-guide/contributing-docs) guide is working fine AFAIK.
