### ISSUE TITLE
cmd ref: document releasing of locks in `dvc run`

### ISSUE THREAD

**Issue by efiop** [iterative/dvc.org#860]
Context: https://github.com/iterative/dvc/pull/2584

**Comment by jorgeorpinel** [comment]
What do you mean by "us"? Thanks

**Comment by jorgeorpinel** [comment]
I see you're assigned here @efiop. You can just send a first draft PR with new/changed text for `dvc run` when you have a chance, and we'll take over to finish it, only pinging you for questions (no review rounds). (So if you use a branch directly on iterative/dvc.org and not from your fork, that'll be easier for us.) Thanks!

**Comment by jorgeorpinel** [comment]
Hi there! @efiop can you confirm the given context is still up to date and/or copy the parts that now affect `repro` and `exp run`? Thanks

**Comment by jorgeorpinel** [comment]
Hello again. Is this the what we're talking about? From https://github.com/iterative/dvc/pull/2584#issuecomment-564391845:

> Adjusted the schema and made rwlock reentrant, so @rwlocked is now placed on public methods of Stage, which is much nicer than what it was before.

I don't think any user has ever needed to know about this so it sounds like an implementation detail we don't need to document.

Please reopen if I'm incorrect.

**Comment by shcheklein** [comment]
I think it's about the user visible behavior - now you could run other DVC commands when `dvc run` itself is running. Before it was not possible. Since this behavior is more optimistic it is not clear if we need any explicit notes. Only in places (if we have it) where we are clearly stating that no commands could run in parallel, or we discuss locks somewhere.

**Comment by jorgeorpinel** [comment]
Hmmm well in general the repo is supposed to be locked during any DVC operation or at least that's implied by https://dvc.org/doc/user-guide/troubleshooting#lock-issue . Is that outdated?

We could separately expand on the description of what `.dvc/tmp/lock` does in https://dvc.org/doc/user-guide/project-structure/internal-files . Other than that I could not find any text mentioning of this limitation so that should be enough to close this.

I started #3251 for this.

**Comment by jorgeorpinel** [comment]
> the repo is supposed to be locked during any DVC operation or at least that's implied by https://dvc.org/doc/user-guide/troubleshooting#lock-issue . Is that outdated?

Hi @dberenbaum (me again 🙂 ) do you know if this info. is outdated? Would be great to get clarification from the core team on what needs to be updated here, if anything (otherwise please close this issue). Thanks

**Comment by dberenbaum** [comment]
> > the repo is supposed to be locked during any DVC operation or at least that's implied by https://dvc.org/doc/user-guide/troubleshooting#lock-issue . Is that outdated?
> 
> Hi @dberenbaum (me again 🙂 ) do you know if this info. is outdated? Would be great to get clarification from the core team on what needs to be updated here, if anything (otherwise please close this issue). Thanks

There is a big improvement here for users, because when the user `cmd` is being executed in a stage, other dvc commands may be run. The repo will still be locked before when dvc is setting up and and after when collecting results of the stage.

However, I don't see any changes needed here because the docs don't address when the repo will or won't be locked, so I think let's close the issue. If we ever put in an in-depth locking guide, we can revisit.

**Comment by jorgeorpinel** [comment]
Good to know, and sounds good. Thanks
